### PR TITLE
Let `@TempDir` fail fast if `createTempDirectory` does not return a directory

### LINKED ISSUE #3900: `@TempDir` should fail fast if `TempDirFactory::createTempDirectory` does not return a directory
The contract of `TempDirFactory::createTempDirectory` mentions:

https://github.com/junit-team/junit5/blob/adf6d4332b8a74db3d43f90982fd87b0d5197b3c/junit-jupiter-api/src/main/java/org/junit/jupiter/api/io/TempDirFactory.java#L61

However, the non-nullability of the returned `Path` is not enforced.

For example, the following:

```java
@Test
void test(@TempDir(factory = Factory.class) Path tempDir) {
}

static class Factory implements TempDirFactory {
    @Override
    public Path createTempDirectory(AnnotatedElementContext elementContext, ExtensionContext extensionContext) throws Exception {
        return null;
    }
}
```

fails with:

```
Jul 26, 2024 5:39:46 PM org.junit.jupiter.engine.execution.JupiterEngineExecutionContext close
SEVERE: Caught exception while closing extension context: org.junit.jupiter.engine.descriptor.MethodExtensionContext@7364985f
java.lang.NullPointerException: Cannot invoke "java.nio.file.Path.getFileSystem()" because "path" is null
```

<details><summary>Stack trace</summary>
<p>

```
Jul 26, 2024 5:39:46 PM org.junit.jupiter.engine.execution.JupiterEngineExecutionContext close
SEVERE: Caught exception while closing extension context: org.junit.jupiter.engine.descriptor.MethodExtensionContext@7364985f
java.lang.NullPointerException: Cannot invoke "java.nio.file.Path.getFileSystem()" because "path" is null
	at java.base/java.nio.file.Files.provider(Files.java:104)
	at java.base/java.nio.file.Files.notExists(Files.java:2551)
	at org.junit.jupiter.engine.extension.TempDirectory$CloseablePath.deleteAllFilesAndDirectories(TempDirectory.java:322)
	at org.junit.jupiter.engine.extension.TempDirectory$CloseablePath.close(TempDirectory.java:310)
	at org.junit.jupiter.engine.descriptor.AbstractExtensionContext.lambda$static$0(AbstractExtensionContext.java:45)
	at org.junit.platform.engine.support.store.NamespacedHierarchicalStore$EvaluatedValue.close(NamespacedHierarchicalStore.java:333)
	at org.junit.platform.engine.support.store.NamespacedHierarchicalStore$EvaluatedValue.access$800(NamespacedHierarchicalStore.java:317)
	at org.junit.platform.engine.support.store.NamespacedHierarchicalStore.lambda$close$3(NamespacedHierarchicalStore.java:98)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.store.NamespacedHierarchicalStore.lambda$close$4(NamespacedHierarchicalStore.java:98)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
	at java.base/java.util.stream.SortedOps$RefSortingSink.end(SortedOps.java:395)
	at java.base/java.util.stream.Sink$ChainedReference.end(Sink.java:261)
	at java.base/java.util.stream.Sink$ChainedReference.end(Sink.java:261)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:510)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
	at org.junit.platform.engine.support.store.NamespacedHierarchicalStore.close(NamespacedHierarchicalStore.java:98)
	at org.junit.jupiter.engine.descriptor.AbstractExtensionContext.close(AbstractExtensionContext.java:87)
	at org.junit.jupiter.engine.execution.JupiterEngineExecutionContext.close(JupiterEngineExecutionContext.java:53)
	at org.junit.jupiter.engine.descriptor.JupiterTestDescriptor.cleanUp(JupiterTestDescriptor.java:224)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$cleanUp$1(TestMethodTestDescriptor.java:156)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.cleanUp(TestMethodTestDescriptor.java:156)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.cleanUp(TestMethodTestDescriptor.java:69)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$cleanUp$10(NodeTestTask.java:167)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.cleanUp(NodeTestTask.java:167)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:98)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:41)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:155)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:41)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:155)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:35)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:54)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:198)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:169)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:93)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.lambda$execute$0(EngineExecutionOrchestrator.java:58)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.withInterceptedStreams(EngineExecutionOrchestrator.java:141)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:57)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:103)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:85)
	at org.junit.platform.launcher.core.DelegatingLauncher.execute(DelegatingLauncher.java:47)
	at org.junit.platform.launcher.core.SessionPerRequestLauncher.execute(SessionPerRequestLauncher.java:63)
	at com.intellij.junit5.JUnit5IdeaTestRunner.startRunnerWithArgs(JUnit5IdeaTestRunner.java:57)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater$1.execute(IdeaTestRunner.java:38)
	at com.intellij.rt.execution.junit.TestsRepeater.repeat(TestsRepeater.java:11)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:35)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:232)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:55)


java.lang.NullPointerException: Cannot invoke "java.nio.file.Path.getFileSystem()" because "path" is null

	at java.base/java.nio.file.Files.provider(Files.java:104)
	at java.base/java.nio.file.Files.notExists(Files.java:2551)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
	at java.base/java.util.stream.SortedOps$RefSortingSink.end(SortedOps.java:395)
	at java.base/java.util.stream.Sink$ChainedReference.end(Sink.java:261)
	at java.base/java.util.stream.Sink$ChainedReference.end(Sink.java:261)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:510)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
```

</p>
</details> 

While it's good that the test doesn't pass, I propose to catch the problem earlier, for example in the `CloseablePath` constructor:

https://github.com/junit-team/junit5/blob/adf6d4332b8a74db3d43f90982fd87b0d5197b3c/junit-jupiter-engine/src/main/java/org/junit/jupiter/engine/extension/TempDirectory.java#L287-L293

I'm happy to submit a PR if the proposal sounds reasonable.

### PR DESCRIPTION
**Pull request by scordio**
## Overview

Resolves #3900.

---

I hereby agree to the terms of the [JUnit Contributor License Agreement](https://github.com/junit-team/junit5/blob/002a0052926ddee57cf90580fa49bc37e5a72427/CONTRIBUTING.md#junit-contributor-license-agreement).

---

### Definition of Done

- [x] There are no TODOs left in the code
- [x] Method [preconditions](https://junit.org/junit5/docs/snapshot/api/org.junit.platform.commons/org/junit/platform/commons/util/Preconditions.html) are checked and documented in the method's Javadoc
- [x] [Coding conventions](https://github.com/junit-team/junit5/blob/HEAD/CONTRIBUTING.md#coding-conventions) (e.g. for logging) have been followed
- [x] Change is covered by [automated tests](https://github.com/junit-team/junit5/blob/HEAD/CONTRIBUTING.md#tests) including corner cases, errors, and exception handling
- [x] Public API has [Javadoc](https://github.com/junit-team/junit5/blob/HEAD/CONTRIBUTING.md#javadoc) and [`@API` annotations](https://apiguardian-team.github.io/apiguardian/docs/current/api/org/apiguardian/api/API.html)
- [x] Change is documented in the [User Guide](https://junit.org/junit5/docs/snapshot/user-guide/) and [Release Notes](https://junit.org/junit5/docs/snapshot/user-guide/#release-notes)

### CODE REVIEW

**Comment by sbrannen** [comment]
If you can update this to reflect #3902 as well, we can hopefully get this into 5.11 RC1.

**Comment by scordio** [comment]
Hi @sbrannen / team, I'm considering changing the testing strategy for these changes.

For the non-nullability check, I introduced additional integration tests in both `TempDirectoryPerDeclarationTests` and `TempDirectoryPerContextTests`, resulting in three new test cases in total.

However, now that the directory requirement should be tested and I want to cover both regular files and symbolic links, there is probably little value in having such a duplication. It might be enough to unit test `TempDirectory.CloseablePath`, similar to `CloseablePathCleanupTests`.

Which direction do you prefer?

**Comment by marcphilipp** [comment]
I would change the tests you added to check for "not a directory" (not important whether it's `null`, a file, or symbolic link) and add unit tests for all specific cases to where the validation happens.

**Comment by marcphilipp** [comment]
@scordio We'd like to release 5.11 RC1 tomorrow. Do you have time today to make the requested changes? If not, please let me know so I can finish it.

**Comment by scordio** [comment]
@marcphilipp yes, I have time 🙂

**Comment by scordio** [comment]
@marcphilipp anything against adding `junit-jupiter-params` as a test dependency of `junit-jupiter-engine`?

**Comment by marcphilipp** [comment]
> @marcphilipp anything against adding `junit-jupiter-params` as a test dependency of `junit-jupiter-engine`?

Unfortunately, yes, since that will break Eclipse which will create a cyclic project dependency since junit-jupiter-params has a test runtime dependency on junit-jupiter-engine. I also wanted to do this last week. For now, please use a dynamic test. Maybe we should introduce a `jupiter-tests` project similar to `platform-tests` to avoid that, but not in this PR.

File: junit-jupiter-engine/src/main/java/org/junit/jupiter/engine/extension/TempDirectory.java [hunk 1]
```diff
@@ -284,15 +284,19 @@ static class CloseablePath implements CloseableResource {
 		private final CleanupMode cleanupMode;
 		private final ExtensionContext extensionContext;
 
-		CloseablePath(TempDirFactory factory, CleanupMode cleanupMode, AnnotatedElementContext elementContext,
+		private CloseablePath(TempDirFactory factory, CleanupMode cleanupMode, AnnotatedElementContext elementContext,
```
Comment (scordio) [inline junit-jupiter-engine/src/main/java/org/junit/jupiter/engine/extension/TempDirectory.java:287]: Looking at the former `CloseablePathCleanupTests`, the intention always seems to use `TempDirectory.createTempDir` as the testing entry point.

For this reason, I've reduced the visibility of this constructor.

**Comment by scordio** [comment]
> For now, please use a dynamic test.

In the end I opted for standard tests, as the setup and cleanup differ between each test case.

File: documentation/src/docs/asciidoc/release-notes/release-notes-5.11.0-RC1.adoc [hunk 2]
```diff
@@ -60,7 +60,8 @@ repository on GitHub.
   `assertInstanceOf` methods introduced in `5.8` version.
 * New generators in `DynamicTest` that take a `Stream`/`Iterator` of `Named<Executable>`
   along with a convenient `NamedExecutable` interface that can simplify writing dynamic
-  tests, in particular in recent version of Java that support records.
+  tests, in particular in recent versions of Java that support records.
```
Comment (marcphilipp) [inline documentation/src/docs/asciidoc/release-notes/release-notes-5.11.0-RC1.adoc:63]: Thanks for fixing my typo! :+1:

File: documentation/src/docs/asciidoc/release-notes/release-notes-5.11.0-RC1.adoc [hunk 3]
```diff
@@ -60,7 +60,8 @@ repository on GitHub.
...
+* `@TempDir` now fails fast when `TempDirFactory::createTempDirectory` returns `null`.
```
Comment (marcphilipp) [inline documentation/src/docs/asciidoc/release-notes/release-notes-5.11.0-RC1.adoc:64]:
```suggestion
* `@TempDir` now fails fast in case `TempDirFactory::createTempDirectory` returns
  `null`, a file, or a symbolic link to a file.
```

File: documentation/src/test/java/example/TempDirectoryDemo.java [hunk 4]
```diff
@@ -137,7 +137,7 @@ static class JimfsTempDirFactory implements TempDirFactory {
 			@Override
 			public Path createTempDirectory(AnnotatedElementContext elementContext, ExtensionContext extensionContext)
 					throws IOException {
-				return Files.createTempDirectory(fileSystem.getPath("/"), "junit");
+				return Files.createTempDirectory(fileSystem.getPath("/"), "junit-");
```
Comment (marcphilipp) [inline documentation/src/test/java/example/TempDirectoryDemo.java:140]: :+1:

**Review by marcphilipp — APPROVED** [review]

File: documentation/src/docs/asciidoc/release-notes/release-notes-5.11.0-RC1.adoc (hunk 2 above)
Comment (scordio) [reply documentation/src/docs/asciidoc/release-notes/release-notes-5.11.0-RC1.adoc:63]: Oh, thanks for catching the release notes gap!

**Comment by marcphilipp** [comment]
@scordio Thanks for your quick and high-quality work on this! :+1:

File: junit-jupiter-engine/src/main/java/org/junit/jupiter/engine/extension/TempDirectory.java [hunk 5]
```diff
@@ -284,14 +284,19 @@ static class CloseablePath implements CloseableResource {
...
 				ExtensionContext extensionContext) throws Exception {
-			this.dir = factory.createTempDirectory(elementContext, extensionContext);
+			this.dir = validateTempDirectory(factory.createTempDirectory(elementContext, extensionContext));
 			this.factory = factory;
 			this.cleanupMode = cleanupMode;
 			this.extensionContext = extensionContext;
 		}
```
Comment (scordio) [inline junit-jupiter-engine/src/main/java/org/junit/jupiter/engine/extension/TempDirectory.java:293]: @marcphilipp I just realized a `PreconditionViolationException` thrown in the constructor would interrupt the execution without closing the factory.

Should we wrap it in a try/catch?

Comment (scordio) [reply junit-jupiter-engine/src/main/java/org/junit/jupiter/engine/extension/TempDirectory.java:293]: I raised #3911 for evaluation.
