### PR TITLE
Provide access to the current ExecutionMode in ExtensionContext

### LINKED ISSUE #2396: Provide information about the current ExecutionMode in ExtensionContext
I am contributing to a bunch of JUnit 5 extensions that rely on a form of field injection to achieve their goals.

Field injection, if done in a `@BeforeEach` callback, works well for both parallel and sequential testing. It also works well for both `PER_CLASS` and `PER_METHOD` lifecycle semantics. However, it does not work very well if you're combining parallel execution with `PER_CLASS` lifecycle semantics, as the parallel execution threads for each test method will each inject their own instances into the single test class instance and clobber each other, interfering with the tests running in other threads. In such situations, it is necessary to inject into a `ThreadLocal` container instead.

Accordingly, I would like my extensions to be able to give fail-fast-and-loud behaviour in these circumstances - throwing an `ExtensionConfigurationException` if it finds it is being asked to run in an environment where it is being asked to run `CONCURRENT` and `PER_CLASS` at the same time, and informing the user that they should use a `ThreadLocal` in such a case.

The problem: the `ExtensionContext` that is passed to the extension's lifecycle methods has a method for telling you which class instance lifecycle mode is in force. However, it doesn't seem to give you a way to easily determine the execution mode. This can be inferred by manually examining the annotations and the global execution mode, but I feel that this breaks encapsulation a little bit - I don't have to do the same for the lifecycle.

## Deliverables

Method `ExecutionMode getExecutionMode()` in `ExtensionContext`.

Possibly a pair of methods - one that returns the value annotated on the class, and one that returns the *actual* execution mode in force (taking into account any global setting). The latter would be more directly useful to my use case.

### PR DESCRIPTION
**Pull request by juliette-derancourt**
## Overview

Resolves #2396.

---

I hereby agree to the terms of the [JUnit Contributor License Agreement](https://github.com/junit-team/junit5/blob/002a0052926ddee57cf90580fa49bc37e5a72427/CONTRIBUTING.md#junit-contributor-license-agreement).

---

### Definition of Done

- [x] There are no TODOs left in the code
- [x] Method [preconditions](https://junit.org/junit5/docs/snapshot/api/org.junit.platform.commons/org/junit/platform/commons/util/Preconditions.html) are checked and documented in the method's Javadoc
- [x] [Coding conventions](https://github.com/junit-team/junit5/blob/HEAD/CONTRIBUTING.md#coding-conventions) (e.g. for logging) have been followed
- [x] Change is covered by [automated tests](https://github.com/junit-team/junit5/blob/HEAD/CONTRIBUTING.md#tests) including corner cases, errors, and exception handling
- [x] Public API has [Javadoc](https://github.com/junit-team/junit5/blob/HEAD/CONTRIBUTING.md#javadoc) and [`@API` annotations](https://apiguardian-team.github.io/apiguardian/docs/current/api/org/apiguardian/api/API.html)
- [ ] Change is documented in the [User Guide](https://junit.org/junit5/docs/snapshot/user-guide/) and [Release Notes](https://junit.org/junit5/docs/snapshot/user-guide/#release-notes)
- [ ] All [continuous integration builds](https://github.com/junit-team/junit5#continuous-integration-builds) pass

### CODE REVIEW

File: junit-jupiter-engine/src/main/java/org/junit/jupiter/engine/descriptor/AbstractExtensionContext.java [hunk 1]
```diff
@@ -127,4 +130,21 @@ public Store getStore(Namespace namespace) {
 	public <V> Optional<V> getConfigurationParameter(String key, Function<String, V> transformer) {
 		return this.configuration.getRawConfigurationParameter(key, transformer);
 	}
+
+	@Override
+	public ExecutionMode getExecutionMode() {
+		return toJupiterExecutionMode(getPlatformExecutionMode());
+	}
+
+	protected abstract Node.ExecutionMode getPlatformExecutionMode();
```
Comment (juliette-derancourt) [inline junit-jupiter-engine/src/main/java/org/junit/jupiter/engine/descriptor/AbstractExtensionContext.java:139]: I'm not sure how to call this one...

File: junit-jupiter-engine/src/main/java/org/junit/jupiter/engine/descriptor/AbstractExtensionContext.java [hunk 2]
```diff
@@ -127,4 +130,21 @@ public Store getStore(Namespace namespace) {
...
+
+	private ExecutionMode toJupiterExecutionMode(Node.ExecutionMode mode) {
```
Comment (juliette-derancourt) [inline junit-jupiter-engine/src/main/java/org/junit/jupiter/engine/descriptor/AbstractExtensionContext.java:141]: It's the reverse of this: https://github.com/junit-team/junit5/blob/main/junit-jupiter-engine/src/main/java/org/junit/jupiter/engine/descriptor/JupiterTestDescriptor.java#L171

Should we perhaps move both somewhere, or leave it here?

File: junit-jupiter-api/src/main/java/org/junit/jupiter/api/extension/ExtensionContext.java [hunk 3]
```diff
@@ -383,6 +384,17 @@ default void publishReportEntry(String value) {
...
 
+	/**
+	 * Get the {@link ExecutionMode} associated with the current test or container.
+	 *
+	 * @return the {@code ExecutionMode} of the test; never {@code null}
+	 *
+	 * @see org.junit.jupiter.api.parallel.ExecutionMode {@code @ExecutionMode}
+	 * @since 5.8
+	 */
+	@API(status = STABLE, since = "5.8")
```
Comment (marcphilipp) [inline junit-jupiter-api/src/main/java/org/junit/jupiter/api/extension/ExtensionContext.java:395]:
```suggestion
	 * @since 5.8.1
	 */
	@API(status = STABLE, since = "5.8.1")
```

**Review by marcphilipp — APPROVED** [review]
