### PR TITLE
Fail `@ParameterizedTest` if there are no registered `ArgumentProviders`

### LINKED ISSUE #4146: Fail ParameterizedTest if there are no registered ArgumentProviders
Not declaring any `@...Source` annotation on a `@ParameterizedTest` method is most likely a user error and should be surfaced as a test failure rather than being silently ignored (now that #1477 permits zero invocations).

## Deliverables

- [ ] Check that there's at least one `ArgumentProvider` registered in `ParameterizedTestExtension` and fail the container otherwise

### PR DESCRIPTION
**Pull request by juliette-derancourt**
## Overview

Resolves #4146 

---

I hereby agree to the terms of the [JUnit Contributor License Agreement](https://github.com/junit-team/junit5/blob/002a0052926ddee57cf90580fa49bc37e5a72427/CONTRIBUTING.md#junit-contributor-license-agreement).

---

### Definition of Done

- [ ] There are no TODOs left in the code
- [ ] Method [preconditions](https://junit.org/junit5/docs/snapshot/api/org.junit.platform.commons/org/junit/platform/commons/util/Preconditions.html) are checked and documented in the method's Javadoc
- [ ] [Coding conventions](https://github.com/junit-team/junit5/blob/HEAD/CONTRIBUTING.md#coding-conventions) (e.g. for logging) have been followed
- [ ] Change is covered by [automated tests](https://github.com/junit-team/junit5/blob/HEAD/CONTRIBUTING.md#tests) including corner cases, errors, and exception handling
- [ ] Public API has [Javadoc](https://github.com/junit-team/junit5/blob/HEAD/CONTRIBUTING.md#javadoc) and [`@API` annotations](https://apiguardian-team.github.io/apiguardian/docs/current/api/org/apiguardian/api/API.html)
- [ ] Change is documented in the [User Guide](https://junit.org/junit5/docs/snapshot/user-guide/) and [Release Notes](https://junit.org/junit5/docs/snapshot/user-guide/#release-notes)

### CODE REVIEW

File: junit-jupiter-params/src/main/java/org/junit/jupiter/params/ParameterizedTestExtension.java [hunk 1]
```diff
@@ -74,8 +75,13 @@ public Stream<TestTemplateInvocationContext> provideTestTemplateInvocationContex
 		ParameterizedTestNameFormatter formatter = createNameFormatter(extensionContext, methodContext);
 		AtomicLong invocationCount = new AtomicLong(0);
 
+		List<ArgumentsSource> argumentsSources = findRepeatableAnnotations(methodContext.method, ArgumentsSource.class);
+
+		Preconditions.condition(!argumentsSources.isEmpty(),
```
Comment (marcphilipp) [inline junit-jupiter-params/src/main/java/org/junit/jupiter/params/ParameterizedTestExtension.java:80]:
```suggestion
		Preconditions.notEmpty(argumentsSources,
```

File: jupiter-tests/src/test/java/org/junit/jupiter/params/ParameterizedTestIntegrationTests.java [hunk 2]
```diff
@@ -457,7 +457,7 @@ void failsWhenArgumentsRequiredButNoneProvided() {
 	}
 
 	@Test
-	void failsWhenArgumentsAreNotRequiredAndNoneProvided() {
+	void doesNotFailWhenArgumentsAreNotRequiredAndNoneProvided() {
```
Comment (marcphilipp) [inline jupiter-tests/src/test/java/org/junit/jupiter/params/ParameterizedTestIntegrationTests.java:460]: :+1:

**Review by marcphilipp — CHANGES_REQUESTED** [review]

**Review by marcphilipp — APPROVED** [review]
