### PR TITLE
Fix support for package-private test methods

### LINKED ISSUE #5098: Test method is silently skipped when parent class has same-named package-private test method
JUnit supports public, protected and package-private test methods.
JUnit supports test class inheritance.
Public and protected methods can be overridden in JLS sense. JUnit recognizes this situation and runs the test only once. In test source code this is indicated with `@Override` (in any reasonably managed project).
Package-private methods do not override each other in JLS sense. Both parent and child classes can declare `@Test void testFoo` method without any warning and without need for `@Override`.  It is expected that such test methods are considered unrelated by JUnit and both are run. Observed behavior is different: only the parent class test is run. The child test is silently ignored.

Using JUnit 6.0.0

## Steps to reproduce

```java
package a;

public abstract class TestParent {
    @Test
    void testParent()
    {
        System.out.println("TestParent.testParent");
    }

    @Test
    public void testPublicNameCollision() {
        System.out.println("TestParent.testPublicNameCollision");
    }

    @Test
    void testPackagePrivateNameCollision() {
        System.out.println("TestParent.testPackagePrivateNameCollision");
    }
}
```

```java
package b;

public class TestChild extends a.TestParent {
    @Test
    void testChild() {
        System.out.println("TestChild.testChild");
    }

    @Test
    @Override // clear source-level indication of test overriding. As expected, only the child test code is run.
    public void testPublicNameCollision() {
        System.out.println("TestChild.testPublicNameCollision");
    }

    @Test
    // no source-level indication of test overriding. This test code does not run, i.e. is silently skipped.
    void testPackagePrivateNameCollision() {
        System.out.println("TestChild.testPackagePrivateNameCollision");
    }
}
```

<details>
<summary>maven setup</summary>

```xml
    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>org.junit</groupId>
                <artifactId>junit-bom</artifactId>
                <version>6.0.0</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>

    <dependencies>
        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter-api</artifactId>
            <scope>test</scope>
        </dependency>
    </dependencies>
```

</details>

`mvn test` prints

```
TestParent.testPackagePrivateNameCollision
TestParent.testParent
TestChild.testChild
TestChild.testPublicNameCollision
```

Note that there is no `TestChild.testPackagePrivateNameCollision` in the output.

## Context

 - Used versions (Jupiter/Vintage/Platform): junit-bom `6.0.0`

### PR DESCRIPTION
**Pull request by marcphilipp**
Prior to this commit, when the test super class wss declared in another
package and declared a package-private test method with the same
signature as the subclass, the method from the subclass was silently
ignored. With the changes in this commit, both test methods are
executed, albeit with the same display name.

Fixes #5098.

---

I hereby agree to the terms of the [JUnit Contributor License Agreement](https://github.com/junit-team/junit-framework/blob/002a0052926ddee57cf90580fa49bc37e5a72427/CONTRIBUTING.md#junit-contributor-license-agreement).

---

### Definition of Done

- [x] There are no TODOs left in the code
- [x] Method [preconditions](https://docs.junit.org/snapshot/api/org.junit.platform.commons/org/junit/platform/commons/util/Preconditions.html) are checked and documented in the method's Javadoc
- [x] [Coding conventions](https://github.com/junit-team/junit-framework/blob/HEAD/CONTRIBUTING.md#coding-conventions) (e.g. for logging) have been followed
- [x] Change is covered by [automated tests](https://github.com/junit-team/junit-framework/blob/HEAD/CONTRIBUTING.md#tests) including corner cases, errors, and exception handling
- [x] Public API has [Javadoc](https://github.com/junit-team/junit-framework/blob/HEAD/CONTRIBUTING.md#javadoc) and [`@API` annotations](https://apiguardian-team.github.io/apiguardian/docs/current/api/org/apiguardian/api/API.html)
- [x] Change is documented in the [User Guide](https://docs.junit.org/snapshot/user-guide/) and [Release Notes](https://docs.junit.org/snapshot/user-guide/#release-notes)

### CODE REVIEW

File: junit-jupiter-engine/src/main/java/org/junit/jupiter/engine/discovery/MethodSelectorResolver.java [hunk 1]
```diff
@@ -223,15 +224,22 @@ Optional<TestDescriptor> resolveUniqueIdIntoTestDescriptor(UniqueId uniqueId, Co
...
-			return parent.getUniqueId().append(segmentType, methodId);
+		private UniqueId createUniqueId(Method method, TestDescriptor parent, Class<?> testClass) {
+			return parent.getUniqueId().append(segmentType, computeMethodId(method, testClass));
+		}
+
+		private static String computeMethodId(Method method, Class<?> testClass) {
+			var parameterTypes = ClassUtils.nullSafeToString(method.getParameterTypes());
+			if (isPackagePrivate(method)
+					&& !method.getDeclaringClass().getPackageName().equals(testClass.getPackageName())) {
+				return "%s#%s(%s)".formatted(method.getDeclaringClass().getName(), method.getName(), parameterTypes);
```
Comment (marcphilipp) [inline junit-jupiter-engine/src/main/java/org/junit/jupiter/engine/discovery/MethodSelectorResolver.java]: The declaring class is added to the unique ID segment of the test method, but only in this case, not in general, to avoid other unique IDs from becoming longer unnecessarily.

File: junit-platform-engine/src/main/java/org/junit/platform/engine/discovery/MethodSelector.java [hunk 2]
```diff
@@ -275,9 +275,17 @@ public boolean equals(Object o) {
...
 		}
 		MethodSelector that = (MethodSelector) o;
-		return Objects.equals(this.className, that.className)//
+		var equal = Objects.equals(this.className, that.className)//
 				&& Objects.equals(this.methodName, that.methodName)//
 				&& Objects.equals(this.parameterTypeNames, that.parameterTypeNames);
+		if (equal) {
+			var thisJavaMethod = this.javaMethod;
+			var thatJavaMethod = that.javaMethod;
+			if (thisJavaMethod != null && thatJavaMethod != null) {
```
Comment (mpkorstanje) [inline junit-platform-engine/src/main/java/org/junit/platform/engine/discovery/MethodSelector.java]: Depending on wether or not `lazyLoadJavaMethod` was called, the equality changes. Is that intentional?

Comment (mpkorstanje) [reply junit-platform-engine/src/main/java/org/junit/platform/engine/discovery/MethodSelector.java]: I suppose a `String declaringClassName` field would have to be added to the  `MethodSelector` to close that gap.

File: junit-jupiter-engine/src/main/java/org/junit/jupiter/engine/discovery/MethodSelectorResolver.java (hunk 1 above)
Comment (mpkorstanje) [reply junit-jupiter-engine/src/main/java/org/junit/jupiter/engine/discovery/MethodSelectorResolver.java]: This would be good to have as a method level comment.

File: junit-platform-engine/src/main/java/org/junit/platform/engine/discovery/MethodSelector.java (hunk 2 above)
Comment (mpkorstanje) [reply junit-platform-engine/src/main/java/org/junit/platform/engine/discovery/MethodSelector.java]: Concrete example:

```java
@Test // Fails but shouldn't
void distinguishesDeclaringClass2() throws Exception {
	var parentMethodSelector = new MethodSelector(TestCase.class,
		ParentTestCase.class.getDeclaredMethod("method", int.class, boolean.class));
	var childMethodSelector = new MethodSelector(TestCase.class, "method", int.class, boolean.class);

	assertThat(parentMethodSelector).isNotEqualTo(childMethodSelector);
	assertThat(childMethodSelector).isNotEqualTo(parentMethodSelector);
}


@Test // passes, but only because the childMethodSelector was mutated.
void distinguishesDeclaringClass3() throws Exception {
	var parentMethodSelector = new MethodSelector(TestCase.class,
		ParentTestCase.class.getDeclaredMethod("method", int.class, boolean.class));
	var childMethodSelector = new MethodSelector(TestCase.class, "method", int.class, boolean.class);

	childMethodSelector.getJavaMethod();
	
	assertThat(parentMethodSelector).isNotEqualTo(childMethodSelector);
	assertThat(childMethodSelector).isNotEqualTo(parentMethodSelector);
}
```

Comment (marcphilipp) [reply junit-platform-engine/src/main/java/org/junit/platform/engine/discovery/MethodSelector.java]: Good catch! Changed in 7b67a8c9ffc348f39cfbd2e3ec8b8fc79c789e4d

File: junit-jupiter-engine/src/main/java/org/junit/jupiter/engine/discovery/MethodSelectorResolver.java (hunk 1 above)
Comment (marcphilipp) [reply junit-jupiter-engine/src/main/java/org/junit/jupiter/engine/discovery/MethodSelectorResolver.java]: Done in aa4a84aa4a64d66f97fdbc1225da6b31cbd9d83c

File: junit-platform-engine/src/main/java/org/junit/platform/engine/discovery/MethodSelector.java
Comment (mpkorstanje) [inline junit-platform-engine/src/main/java/org/junit/platform/engine/discovery/MethodSelector.java:293]: We could consider including `declaringClassName` here. 

Though I do think it is an implementation detail, it would make debugging the test easier..

File: junit-platform-engine/src/main/java/org/junit/platform/engine/discovery/MethodSelector.java [hunk 3]
```diff
@@ -75,51 +76,51 @@ public final class MethodSelector implements DiscoverySelector {
...
+		this.parameterTypes = parameterTypes;
+	}
+
+	private MethodSelector(@Nullable ClassLoader classLoader, String className, String methodName,
+			String parameterTypeNames, @Nullable String declaringClassName) {
+		this.classLoader = classLoader;
+		this.className = className;
+		this.methodName = methodName;
+		this.parameterTypeNames = parameterTypeNames;
+		this.declaringClassName = className.equals(declaringClassName) ? null : declaringClassName;
```
Comment (mpkorstanje) [inline junit-platform-engine/src/main/java/org/junit/platform/engine/discovery/MethodSelector.java]: This echo's the considerations of `formatMethodSpecPart` but here we check for equality on class names rather than package names. This doesn't seem quite right (yet). 

Though the `MethodSelectorTests` uses a private method in the `ParentTestCase` rather than putting the `ParentTestCase` in a different package. So I can't work out if that was intentional.

**Review by mpkorstanje — CHANGES_REQUESTED** [review]
I've pushed 31128d6 to make the build green. But I've got some reservations about the way I've done so.  For a lack of a better word, I would expect a symmetry of concerns between the unique id segment of a method and the method selector. Currently that symmetry is broken.

**Comment by marcphilipp** [comment]
> I've pushed [31128d6](https://github.com/junit-team/junit-framework/commit/31128d6a991afad7a30d62b803ad0344429c0f4c) to make the build green. But I've got some reservations about the way I've done so. For a lack of a better word, I would expect a symmetry of concerns between the unique id segment of a method and the method selector. Currently that symmetry is broken.

Thanks! I have similar reservations. Therefore, I've pushed two commits that solve the issue by introducing a Jupiter-specific, internal `DeclaredMethodSelector`.

@mpkorstanje WDYT?

**Comment by marcphilipp** [comment]
> I would expect that while using the `EngineDiscoveryRequestResolver` I should be able to produce the same test plan by using either one class selector, or a collection of method selectors. Because the `MethodSelector` `equals` implementation lacks fidelity that isn't possible yet.

I agree but the scenario here is truly an edge case and I think we can postpone tackling the adjacent issue. When we do, we also need to think about `NestedMethodSelector`.

**Comment by mpkorstanje** [comment]
> I agree but the scenario here is truly an edge case and I think we can postpone tackling the adjacent issue. When we do, we also need to think about NestedMethodSelector.

And `MethodSource` apparently :smile:
