### PR TITLE
Avoid GPG agent interactions during test runs

### LINKED ISSUE #5069: Running gradlew test promps GPG key unlock
Running `./gradlew test` requires unlocking GPG keys, this makes running tests annoying.

## Steps to reproduce

1. Create a a GPG key with a password
2. Setup git to sign commits with that GPG key.
3. Run `./gradlew test` 

Observe: 

1. A prompt to unlock the GPG key.
2. `OpenTestReportGeneratingListenerTests.includesGitInfoWhenEnabled` failing if the prompt is rejected

## Deliverables

- [ ] Don't create signed commits when testing

### PR DESCRIPTION
**Pull request by marcphilipp**
Resolves #5069.

---

I hereby agree to the terms of the [JUnit Contributor License Agreement](https://github.com/junit-team/junit-framework/blob/002a0052926ddee57cf90580fa49bc37e5a72427/CONTRIBUTING.md#junit-contributor-license-agreement).

---

### Definition of Done

- [x] There are no TODOs left in the code
- [x] Method [preconditions](https://docs.junit.org/snapshot/api/org.junit.platform.commons/org/junit/platform/commons/util/Preconditions.html) are checked and documented in the method's Javadoc
- [x] [Coding conventions](https://github.com/junit-team/junit-framework/blob/HEAD/CONTRIBUTING.md#coding-conventions) (e.g. for logging) have been followed
- [x] Change is covered by [automated tests](https://github.com/junit-team/junit-framework/blob/HEAD/CONTRIBUTING.md#tests) including corner cases, errors, and exception handling
- [x] Public API has [Javadoc](https://github.com/junit-team/junit-framework/blob/HEAD/CONTRIBUTING.md#javadoc) and [`@API` annotations](https://apiguardian-team.github.io/apiguardian/docs/current/api/org/apiguardian/api/API.html)
- [x] Change is documented in the [User Guide](https://docs.junit.org/snapshot/user-guide/) and [Release Notes](https://docs.junit.org/snapshot/user-guide/#release-notes)

### CODE REVIEW

File: platform-tests/src/test/java/org/junit/platform/reporting/open/xml/OpenTestReportGeneratingListenerTests.java [hunk 1]
```diff
@@ -191,7 +191,7 @@ void includesGitInfoWhenEnabled(String originUrl, @TempDir Path tempDirectory) t
 
 		execGit(tempDirectory, "config", "user.name", "Alice");
 		execGit(tempDirectory, "config", "user.email", "alice@example.org");
-		execGit(tempDirectory, "commit", "-m", "Initial commit");
```
Comment (mpkorstanje) [inline platform-tests/src/test/java/org/junit/platform/reporting/open/xml/OpenTestReportGeneratingListenerTests.java:194]: This will work, but maybe creating an empty config file in the tmp dir and setting `GIT_CONFIG_GLOBAL` would be more durable.

https://git-scm.com/docs/git#Documentation/git.txt-GITCONFIGGLOBAL

**Review by mpkorstanje — APPROVED** [review]

File: platform-tests/src/test/java/org/junit/platform/reporting/open/xml/OpenTestReportGeneratingListenerTests.java (hunk 1 above)
Comment (marcphilipp) [reply platform-tests/src/test/java/org/junit/platform/reporting/open/xml/OpenTestReportGeneratingListenerTests.java:194]: Good idea! Done in 389806becb5218c8d9429202f2c66a40df1b832f.
