### PR TITLE
Truncate arguments in display name if they exceed max length

### LINKED ISSUE #2358: Excessively long argument values in parameterized display names should be truncated
JUnit provides a nice way to configure test names, however, the names might become too long unexpectedly.

Here's a case for JUnit4:

https://github.com/pgjdbc/pgjdbc/blob/aa190cce2c27ac5f5d4fa33f5d156f8bf04cbe0c/pgjdbc/src/test/java/org/postgresql/core/UTF8EncodingTest.java#L29-L33

```java
  @Parameterized.Parameters(name = "string={1}, encoding={0}")
  public static Iterable<Object[]> data() {
    final StringBuilder reallyLongString = new StringBuilder(1024 * 1024);
    for (int i = 0; i < 185000; ++i) {
      reallyLongString.append(i);
    }
```

I guess the same is relevant for JUnit5 as well.

It would be great if JUnit could detect such cases, and it could trim the sub-parts before it produces a single multi-megabyte test name.

For instance, in the case like above JUnit could produce something like `string=012345678910111213...truncated...sha1=12312312123, encoding=utf-8`

It turns out the long test names consume disk space as Gradle records all the test outputs, and it does make `remote build cache` slower, as the build cache has to keep all the long test names (so it impacts `cache space consumption`, `cache store latency` and `cache retrieval latency`).

Of course, users can truncate test names on their own, however, I believe it would be better if JUnit prevented "unexpectedly long test name" issue automatically.

In other words:

1) If use is using placeholder-like pattern, then JUnit should trim all the parameters.
2) If the user returns test name via programmatic API (I'm not sure if that exists at all, but I assume it does :) ), then JUnit could truncate the full string.
3) There should probably be a configuration option for the default limit of the parameter value.

WDYT?

Relevant Gradle Build Cache issue: https://github.com/gradle/gradle/issues/13608#issuecomment-660874776

### PR DESCRIPTION
**Pull request by marcphilipp**
Resolves #2358.

---

I hereby agree to the terms of the [JUnit Contributor License Agreement](https://github.com/junit-team/junit5/blob/002a0052926ddee57cf90580fa49bc37e5a72427/CONTRIBUTING.md#junit-contributor-license-agreement).

---

### Definition of Done

- [x] There are no TODOs left in the code
- [x] Method [preconditions](https://junit.org/junit5/docs/snapshot/api/org.junit.platform.commons/org/junit/platform/commons/util/Preconditions.html) are checked and documented in the method's Javadoc
- [x] [Coding conventions](https://github.com/junit-team/junit5/blob/HEAD/CONTRIBUTING.md#coding-conventions) (e.g. for logging) have been followed
- [x] Change is covered by [automated tests](https://github.com/junit-team/junit5/blob/HEAD/CONTRIBUTING.md#tests) including corner cases, errors, and exception handling
- [x] Public API has [Javadoc](https://github.com/junit-team/junit5/blob/HEAD/CONTRIBUTING.md#javadoc) and [`@API` annotations](https://apiguardian-team.github.io/apiguardian/docs/current/api/org/apiguardian/api/API.html)
- [x] Change is documented in the [User Guide](https://junit.org/junit5/docs/snapshot/user-guide/) and [Release Notes](https://junit.org/junit5/docs/snapshot/user-guide/#release-notes)
- [ ] All [continuous integration builds](https://github.com/junit-team/junit5#continuous-integration-builds) pass

### CODE REVIEW

File: junit-jupiter-params/src/test/java/org/junit/jupiter/params/ParameterizedTestIntegrationTests.java [hunk 1]
```diff
@@ -219,6 +220,17 @@ void executesLifecycleMethods() {
...
 	}
 
+	@Test
+	void truncatesArgumentsThatExceedMaxLength() {
+		var results = EngineTestKit.engine(new JupiterTestEngine()) //
+				.configurationParameter(ParameterizedTestExtension.ARGUMENT_MAX_LENGTH_KEY, "2") //
+				.selectors(selectMethod(TestCase.class, "testWithCsvSource", String.class.getName())) //
+				.execute();
+		results.testEvents().assertThatEvents() //
+				.haveExactly(1, event(displayName("[1] argument=f…"), started())) //
```
Comment (juliette-derancourt) [inline junit-jupiter-params/src/test/java/org/junit/jupiter/params/ParameterizedTestIntegrationTests.java:230]: So do we consider that `…` counts as a character? Personally, with a max length of _two_ I'd naturally expect `fo…`. But I may be the only one 🤷‍♀️

Comment (marcphilipp) [reply junit-jupiter-params/src/test/java/org/junit/jupiter/params/ParameterizedTestIntegrationTests.java:230]: TBH I was myself torn on this question. @junit-team/junit-lambda Thoughts?

Comment (sormuras) [reply junit-jupiter-params/src/test/java/org/junit/jupiter/params/ParameterizedTestIntegrationTests.java:230]: If I specify a max char count, I expect to get back a string of the given max length. For max = 5 and `...` it'd yield:

```
   "123" = "123"
  "1234" = "1234"
 "12345" = "12345"
"123456" = "12..."
```

Comment (marcphilipp) [reply junit-jupiter-params/src/test/java/org/junit/jupiter/params/ParameterizedTestIntegrationTests.java:230]: I'm using the Unicode ellipsis character `…` which is just one character so it would be `1234…` for `123456` in your example.

Comment (sormuras) [reply junit-jupiter-params/src/test/java/org/junit/jupiter/params/ParameterizedTestIntegrationTests.java:230]: Ah, I see. Nice trick to retain two characters from the source string. I'll update the example above accordingly.

Gist: a given max char count should not be exceeded. It's max. Not max+n. ;-)

Comment (sbrannen) [reply junit-jupiter-params/src/test/java/org/junit/jupiter/params/ParameterizedTestIntegrationTests.java:230]: > Gist: a given max char count should not be exceeded. It's max. Not max+n. ;-)

Comment (sbrannen) [reply junit-jupiter-params/src/test/java/org/junit/jupiter/params/ParameterizedTestIntegrationTests.java:230]: >Gist: a given max char count should not be exceeded. It's max. Not max+n.

I agree with that.

File: documentation/src/docs/asciidoc/release-notes/release-notes-5.7.0-M2.adoc [hunk 2]
```diff
@@ -107,6 +107,10 @@ on GitHub.
   thread in the cause of the `AssertionFailedError`.
 * New `TypedArgumentConverter` for converting one specific type to another, therefore
   reducing boilerplate type checks compared to implementing `ArgumentConverter` directly.
+* Added `ExtensionContext.getConfigurationParameter(String, Function<String, T>)`
+  convenience method for reading transformed configuration parameters from extensions.
+* Arguments of in display names of parameterized test invocations are now truncated if
```
Comment (sbrannen) [inline documentation/src/docs/asciidoc/release-notes/release-notes-5.7.0-M2.adoc:112]:
```suggestion
* Arguments in display names of parameterized test invocations are now truncated if
```

File: junit-jupiter-params/src/main/java/org/junit/jupiter/params/ParameterizedTestNameFormatter.java [hunk 3]
```diff
@@ -91,10 +94,17 @@ private String argumentsPattern(Object[] arguments) {
...
-				result[i] = StringUtils.nullSafeToString(arguments[i]);
+				result[i] = truncateIfExceedsMaxLength(StringUtils.nullSafeToString(arguments[i]));
 			}
 		}
 		return result;
 	}
 
+	private String truncateIfExceedsMaxLength(String argument) {
+		if (argument.length() > argumentMaxLength) {
+			return argument.substring(0, argumentMaxLength - 1) + "\u2026";
```
Comment (sbrannen) [inline junit-jupiter-params/src/main/java/org/junit/jupiter/params/ParameterizedTestNameFormatter.java:105]: Maybe add a comment that the unicode character is an ellipsis.

File: documentation/src/docs/asciidoc/user-guide/writing-tests.adoc [hunk 4]
```diff
@@ -1563,6 +1563,11 @@ The following placeholders are supported within custom display names.
 | `{0}`, `{1}`, ...        | an individual argument
 |===
 
+NOTE: When including arguments in display names, their string representation is truncated
+if it exceeds the configured maximum length. The limit is configurable via the
```
Comment (sbrannen) [inline documentation/src/docs/asciidoc/user-guide/writing-tests.adoc:1567]:
```suggestion
NOTE: When including arguments in display names, their string representations are truncated
if they exceed the configured maximum length. The limit is configurable via the
```

File: junit-jupiter-params/src/test/java/org/junit/jupiter/params/ParameterizedTestIntegrationTests.java (hunk 1 above)
Comment (juliette-derancourt) [reply junit-jupiter-params/src/test/java/org/junit/jupiter/params/ParameterizedTestIntegrationTests.java:230]: So be it 😄 
But we should make that clear in the documentation then.

File: junit-jupiter-params/src/main/java/org/junit/jupiter/params/ParameterizedTestNameFormatter.java (hunk 3 above)
Comment (marcphilipp) [reply junit-jupiter-params/src/main/java/org/junit/jupiter/params/ParameterizedTestNameFormatter.java]: Done in 4f4707e082ae70e3f34925f0d1f37039b5d70691.

**Comment by marcphilipp** [comment]
@sbrannen PTAL
