### PR TITLE
Fix global read-write lock handling when not declared on top level

### LINKED ISSUE #4027: Declaring the global read-write lock on a leaf node should not fail execution
I've upgraded my Cucumber test framework with JUnit 5.11.1 and I get a new error:
```
[ERROR]   Task was deferred but should have been executed synchronously: NodeTestTask [PickleDescriptor: [engine:junit-platform-suite]/[suite:com.ionos.cloud.cucumber.ml.MlApiTest]/[engine:cucumber]/[feature:classpath%3Afeatures%2FModel%2FModelLB.feature]/[scenario:26]]

```
All I can say is that inside the feature file I have two scenarios: one marked with `@isolated`  global read write exclusive resource and another scenario is marked with a simple read write exclusive resource.

Reverting to JUnit 5.11.0 works without any error !

I'm sorry I cannot give more details. Maybe I will try to isolate it to a more detailed scenario when I'll have more time.

### PR DESCRIPTION
**Pull request by marcphilipp**
## Overview

Prior to this change additional locks were not cleared from siblings 
when discovering the global read-write lock on a test descriptor which 
led to incompatible locks and caused test execution to fail.

Fixes #4027.

---

I hereby agree to the terms of the [JUnit Contributor License Agreement](https://github.com/junit-team/junit5/blob/002a0052926ddee57cf90580fa49bc37e5a72427/CONTRIBUTING.md#junit-contributor-license-agreement).

---

### Definition of Done

- [x] There are no TODOs left in the code
- [x] Method [preconditions](https://junit.org/junit5/docs/snapshot/api/org.junit.platform.commons/org/junit/platform/commons/util/Preconditions.html) are checked and documented in the method's Javadoc
- [x] [Coding conventions](https://github.com/junit-team/junit5/blob/HEAD/CONTRIBUTING.md#coding-conventions) (e.g. for logging) have been followed
- [x] Change is covered by [automated tests](https://github.com/junit-team/junit5/blob/HEAD/CONTRIBUTING.md#tests) including corner cases, errors, and exception handling
- [x] Public API has [Javadoc](https://github.com/junit-team/junit5/blob/HEAD/CONTRIBUTING.md#javadoc) and [`@API` annotations](https://apiguardian-team.github.io/apiguardian/docs/current/api/org/apiguardian/api/API.html)
- [x] Change is documented in the [User Guide](https://junit.org/junit5/docs/snapshot/user-guide/) and [Release Notes](https://junit.org/junit5/docs/snapshot/user-guide/#release-notes)

### CODE REVIEW

File: platform-tests/src/test/java/org/junit/platform/engine/support/hierarchical/ParallelExecutionIntegrationTests.java [hunk 1]
```diff
@@ -283,6 +280,14 @@ void runsIsolatedTestsLastToMaximizeParallelism() {
 		assertThat(isolatedClassStart).isAfterOrEqualTo(parallelClassFinish);
 	}
 
+	@ParameterizedTest
+	@ValueSource(classes = { IsolatedMethodFirstTestCase.class, IsolatedMethodLastTestCase.class })
+	void canRunTestsIsolatedFromEachOtherWhenDeclaredOnFirstMethod(Class<?> testClass) {
```
Comment (mpkorstanje) [inline platform-tests/src/test/java/org/junit/platform/engine/support/hierarchical/ParallelExecutionIntegrationTests.java:285]: The `WhenDeclaredOnFirstMethod` seems to contradict the `IsolatedMethodFirstTestCase` and `IsolatedMethodLastTestCase`.

Comment (marcphilipp) [reply platform-tests/src/test/java/org/junit/platform/engine/support/hierarchical/ParallelExecutionIntegrationTests.java:285]: Thanks for spotting that! I refactored from two test methods to a parameterized one and forgot to rename the method.

Comment (marcphilipp) [reply platform-tests/src/test/java/org/junit/platform/engine/support/hierarchical/ParallelExecutionIntegrationTests.java:285]:
```suggestion
	void canRunTestsIsolatedFromEachOtherWhenDeclaredOnMethodLevel(Class<?> testClass) {
```

**Review by mpkorstanje — APPROVED** [review]

**Review by leonard84 — APPROVED** [review]
