### PR TITLE
Fix class-level execution conditions on GraalVM

### LINKED ISSUE #3745: `@EnabledInNativeImage` is not properly supported at the class level
## Steps to reproduce

- `@EnabledInNativeImage` is only valid when marked on the function body and has no effect when marked on the class. This means that the following snippet has no problem.
```java
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.condition.EnabledInNativeImage;

import static org.junit.jupiter.api.Assertions.assertEquals;

public class FunctionLevelTest {
    @Test
    @EnabledInNativeImage
    void testOnFunction() {
        assertEquals(1 + 2, 3);
    }
}
```
- But in the following snippet, `@EnabledInNativeImage` is invalid.
```java
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.condition.EnabledInNativeImage;

import static org.junit.jupiter.api.Assertions.assertEquals;

@EnabledInNativeImage
public class ClassLevelTest {

    @Test
    void testOnClass(){
        assertEquals(1 + 2, 3);
    }
}
```
- I created https://github.com/linghengqian/junit5-native-image-annotation-test to demonstrate. Here are the steps to reproduce.
```shell
sdk install java 21.0.2-graalce
sdk use java 21.0.2-graalce

git clone git@github.com:linghengqian/junit5-native-image-annotation-test.git
cd ./junit5-native-image-annotation-test/
./mvnw -T1C -e clean test
./mvnw -PnativeTestInJunit -T1C -e clean test
```

- In the final Log, we can see that `com.lingh.ClassLevelTest.testOnClass()` is not executed in nativeTest.
```shell
Finished generating 'native-tests' in 25.1s.
[INFO] Executing: /home/linghengqian/IdeaProjects/junit5-native-image-annotation-test/target/native-tests --xml-output-dir /home/linghengqian/IdeaProjects/junit5-native-image-annotation-test/target/native-test-reports -Djunit.platform.listeners.uid.tracking.output.dir=/home/linghengqian/IdeaProjects/junit5-native-image-annotation-test/target/test-ids
JUnit Platform on Native Image - report
----------------------------------------

com.lingh.FunctionLevelTest > testOnFunction() SUCCESSFUL


Test run finished after 1 ms
[         2 containers found      ]
[         0 containers skipped    ]
[         2 containers started    ]
[         0 containers aborted    ]
[         2 containers successful ]
[         0 containers failed     ]
[         1 tests found           ]
[         0 tests skipped         ]
[         1 tests started         ]
[         0 tests aborted         ]
[         1 tests successful      ]
[         0 tests failed          ]
```

- More early investigations are from https://github.com/apache/shardingsphere/pull/30031 and https://github.com/apache/shardingsphere/issues/29052 .

## Context

 - Used versions (Jupiter/Vintage/Platform): `Jupiter`
 - Build Tool/IDE: `Maven Wrapper 3.9.5`/`IntelliJ IDEA 2023.3.6 (Ultimate Edition)`

## Deliverables

- Null.

### PR DESCRIPTION
**Pull request by marcphilipp**
- **Update to latest version of native build tools**
- **Add failing integration test**
- **Track descendants of skipped containers**
- **Add to release notes**

Fixes #3745.

### CODE REVIEW

File: junit-platform-launcher/src/main/java/org/junit/platform/launcher/listeners/UniqueIdTrackingListener.java [hunk 1]
```diff
@@ -138,22 +139,37 @@ public UniqueIdTrackingListener() {
...
+			this.testPlan.getChildren(testIdentifier).forEach(this::trackTestUidRecursively);
+		}
 	}
 
-	private void trackTestUid(TestIdentifier testIdentifier) {
-		if (this.enabled && testIdentifier.isTest()) {
-			this.uniqueIds.add(testIdentifier.getUniqueId());
+	private boolean trackTestUid(TestIdentifier testIdentifier) {
+		if (testIdentifier.isTest()) {
+			return this.uniqueIds.add(testIdentifier.getUniqueId());
```
Comment (sbrannen) [inline junit-platform-launcher/src/main/java/org/junit/platform/launcher/listeners/UniqueIdTrackingListener.java:170]: This will always return `true` since it's an `ArrayList`.

Did you perhaps mean to switch to a `LinkedHashSet`?

If not, perhaps we should change that to the following for better clarity.

```suggestion
			this.uniqueIds.add(testIdentifier.getUniqueId());
			return true;
```

File: platform-tooling-support-tests/projects/graalvm-starter/build.gradle.kts [hunk 2]
```diff
@@ -31,8 +31,6 @@ tasks.test {
 graalvmNative {
 	binaries {
 		named("test") {
-			buildArgs.add("--initialize-at-build-time=org.junit.platform.launcher.core.LauncherConfig")
-			buildArgs.add("--initialize-at-build-time=org.junit.jupiter.engine.config.InstantiatingConfigurationParameterConverter")
```
Comment (sbrannen) [inline platform-tooling-support-tests/projects/graalvm-starter/build.gradle.kts:35]: Even though recent versions of Native Build Tools register those as well, I don't think we should remove this configuration.

- see https://github.com/junit-team/junit5/issues/3040

**Review by sbrannen — CHANGES_REQUESTED** [review]
Thanks for putting together this PR!

I added two comments for consideration.

File: platform-tooling-support-tests/projects/graalvm-starter/build.gradle.kts (hunk 2 above)
Comment (marcphilipp) [reply platform-tooling-support-tests/projects/graalvm-starter/build.gradle.kts:35]: Why should we keep it? The reason for adding this here was because Native Build Tools didn't already configure those. I think adding a [`native-image.properties`](https://www.graalvm.org/22.1/reference-manual/native-image/BuildConfiguration/#embedding-a-configuration-file) file is a separate issue.

File: junit-platform-launcher/src/main/java/org/junit/platform/launcher/listeners/UniqueIdTrackingListener.java (hunk 1 above)
Comment (marcphilipp) [reply junit-platform-launcher/src/main/java/org/junit/platform/launcher/listeners/UniqueIdTrackingListener.java:170]: I know that it will always return `true`. I kept the `ArrayList` to avoid changing to much. That being said, I think your suggestion does make it clearer so I'll follow it.

File: platform-tooling-support-tests/projects/graalvm-starter/build.gradle.kts (hunk 2 above)
Comment (sbrannen) [reply platform-tooling-support-tests/projects/graalvm-starter/build.gradle.kts:35]: Ahhh... yes, you're right.

This is just our test build script. I apologize for not thinking that through.

Please just disregard that comment, and I'll _hide_ it. 😉

**Review by sbrannen — APPROVED** [review]
