### PR TITLE
Avoid reporting discovery warnings for abstract methods

### LINKED ISSUE #4636: Discovery issue incorrectly reported for abstract `@Test` method in abstract class
## Overview

In the Spring Framework test suite, [`EnableJmsTests`](https://github.com/spring-projects/spring-framework/blob/main/spring-jms/src/test/java/org/springframework/jms/annotation/EnableJmsTests.java) and [`AnnotationDrivenNamespaceTests`](https://github.com/spring-projects/spring-framework/blob/main/spring-jms/src/test/java/org/springframework/jms/annotation/AnnotationDrivenNamespaceTests.java) extend [`AbstractJmsAnnotationDrivenTests`](https://github.com/spring-projects/spring-framework/blob/main/spring-jms/src/test/java/org/springframework/jms/annotation/AbstractJmsAnnotationDrivenTests.java) which declares `abstract` `@Test` methods.

The `@Test` annotations are used as a form of documentation to signal that concrete implementations of those test methods must be annotated with `@Test`.

Running `EnableJmsTests` and `AnnotationDrivenNamespaceTests` by themselves does not result in any discovery issue warnings.

However, when running the test suite, `AbstractJmsAnnotationDrivenTests` also gets analyzed and results in the following invalid warnings.

```
WARNING: TestEngine with ID 'junit-jupiter' encountered 9 non-critical issues during test discovery:

(1) [WARNING] @Test method 'abstract void org.springframework.jms.annotation.AbstractJmsAnnotationDrivenTests.jmsListeners()' must not be abstract. It will not be executed.
    Source: MethodSource [className = 'org.springframework.jms.annotation.AbstractJmsAnnotationDrivenTests', methodName = 'jmsListeners', methodParameterTypes = '']
            at org.springframework.jms.annotation.AbstractJmsAnnotationDrivenTests.jmsListeners(SourceFile:0)

(2) [WARNING] @Test method 'abstract void org.springframework.jms.annotation.AbstractJmsAnnotationDrivenTests.sampleConfiguration()' must not be abstract. It will not be executed.
    Source: MethodSource [className = 'org.springframework.jms.annotation.AbstractJmsAnnotationDrivenTests', methodName = 'sampleConfiguration', methodParameterTypes = '']
            at org.springframework.jms.annotation.AbstractJmsAnnotationDrivenTests.sampleConfiguration(SourceFile:0)

(3) [WARNING] @Test method 'abstract void org.springframework.jms.annotation.AbstractJmsAnnotationDrivenTests.customConfiguration()' must not be abstract. It will not be executed.
    Source: MethodSource [className = 'org.springframework.jms.annotation.AbstractJmsAnnotationDrivenTests', methodName = 'customConfiguration', methodParameterTypes = '']
            at org.springframework.jms.annotation.AbstractJmsAnnotationDrivenTests.customConfiguration(SourceFile:0)

(4) [WARNING] @Test method 'abstract void org.springframework.jms.annotation.AbstractJmsAnnotationDrivenTests.jmsHandlerMethodFactoryConfiguration()' must not be abstract. It will not be executed.
    Source: MethodSource [className = 'org.springframework.jms.annotation.AbstractJmsAnnotationDrivenTests', methodName = 'jmsHandlerMethodFactoryConfiguration', methodParameterTypes = '']
            at org.springframework.jms.annotation.AbstractJmsAnnotationDrivenTests.jmsHandlerMethodFactoryConfiguration(SourceFile:0)

(5) [WARNING] @Test method 'abstract void org.springframework.jms.annotation.AbstractJmsAnnotationDrivenTests.explicitContainerFactory()' must not be abstract. It will not be executed.
    Source: MethodSource [className = 'org.springframework.jms.annotation.AbstractJmsAnnotationDrivenTests', methodName = 'explicitContainerFactory', methodParameterTypes = '']
            at org.springframework.jms.annotation.AbstractJmsAnnotationDrivenTests.explicitContainerFactory(SourceFile:0)

(6) [WARNING] @Test method 'abstract void org.springframework.jms.annotation.AbstractJmsAnnotationDrivenTests.fullConfiguration()' must not be abstract. It will not be executed.
    Source: MethodSource [className = 'org.springframework.jms.annotation.AbstractJmsAnnotationDrivenTests', methodName = 'fullConfiguration', methodParameterTypes = '']
            at org.springframework.jms.annotation.AbstractJmsAnnotationDrivenTests.fullConfiguration(SourceFile:0)

(7) [WARNING] @Test method 'abstract void org.springframework.jms.annotation.AbstractJmsAnnotationDrivenTests.defaultContainerFactory()' must not be abstract. It will not be executed.
    Source: MethodSource [className = 'org.springframework.jms.annotation.AbstractJmsAnnotationDrivenTests', methodName = 'defaultContainerFactory', methodParameterTypes = '']
            at org.springframework.jms.annotation.AbstractJmsAnnotationDrivenTests.defaultContainerFactory(SourceFile:0)

(8) [WARNING] @Test method 'abstract void org.springframework.jms.annotation.AbstractJmsAnnotationDrivenTests.fullConfigurableConfiguration()' must not be abstract. It will not be executed.
    Source: MethodSource [className = 'org.springframework.jms.annotation.AbstractJmsAnnotationDrivenTests', methodName = 'fullConfigurableConfiguration', methodParameterTypes = '']
            at org.springframework.jms.annotation.AbstractJmsAnnotationDrivenTests.fullConfigurableConfiguration(SourceFile:0)

(9) [WARNING] @Test method 'abstract void org.springframework.jms.annotation.AbstractJmsAnnotationDrivenTests.jmsListenerIsRepeatable()' must not be abstract. It will not be executed.
    Source: MethodSource [className = 'org.springframework.jms.annotation.AbstractJmsAnnotationDrivenTests', methodName = 'jmsListenerIsRepeatable', methodParameterTypes = '']
            at org.springframework.jms.annotation.AbstractJmsAnnotationDrivenTests.jmsListenerIsRepeatable(SourceFile:0)
```

Similar to #4635, I think the discovery issue check should be updated so that it does not report that, if the class in question is `abstract`.

## Related Issues

- #4635

### PR DESCRIPTION
**Pull request by marcphilipp**
## Overview

Resolves #4636.

---

I hereby agree to the terms of the [JUnit Contributor License Agreement](https://github.com/junit-team/junit5/blob/002a0052926ddee57cf90580fa49bc37e5a72427/CONTRIBUTING.md#junit-contributor-license-agreement).

---

### Definition of Done

- [x] There are no TODOs left in the code
- [x] Method [preconditions](https://docs.junit.org/snapshot/api/org.junit.platform.commons/org/junit/platform/commons/util/Preconditions.html) are checked and documented in the method's Javadoc
- [x] [Coding conventions](https://github.com/junit-team/junit5/blob/HEAD/CONTRIBUTING.md#coding-conventions) (e.g. for logging) have been followed
- [x] Change is covered by [automated tests](https://github.com/junit-team/junit5/blob/HEAD/CONTRIBUTING.md#tests) including corner cases, errors, and exception handling
- [x] Public API has [Javadoc](https://github.com/junit-team/junit5/blob/HEAD/CONTRIBUTING.md#javadoc) and [`@API` annotations](https://apiguardian-team.github.io/apiguardian/docs/current/api/org/apiguardian/api/API.html)
- [x] Change is documented in the [User Guide](https://docs.junit.org/snapshot/user-guide/) and [Release Notes](https://docs.junit.org/snapshot/user-guide/#release-notes)

### CODE REVIEW

File: jupiter-tests/src/test/java/org/junit/jupiter/engine/discovery/predicates/IsTestMethodTests.java [hunk 1]
```diff
@@ -86,12 +81,8 @@ void bogusAbstractNonVoidTestMethod() {
...
 		assertThat(isTestMethod).rejects(method);
 
-		assertThat(discoveryIssues).hasSize(2);
-		discoveryIssues.sort(comparing(DiscoveryIssue::message));
-		assertThat(discoveryIssues.getFirst().message()) //
-				.isEqualTo("@Test method '%s' must not be abstract. It will not be executed.",
-					method.toGenericString());
-		assertThat(discoveryIssues.getLast().message()) //
+		var issue = getOnlyElement(discoveryIssues);
+		assertThat(issue.message()) //
```
Comment (ronodhirSoumik) [inline jupiter-tests/src/test/java/org/junit/jupiter/engine/discovery/predicates/IsTestMethodTests.java:85]: `//` is this necessary?

Comment (sormuras) [reply jupiter-tests/src/test/java/org/junit/jupiter/engine/discovery/predicates/IsTestMethodTests.java:85]: In some, much more than I like, cases like this, yes. It's due to a limitation of the underlying code formatter being used: `spotless`

Comment (marcphilipp) [reply jupiter-tests/src/test/java/org/junit/jupiter/engine/discovery/predicates/IsTestMethodTests.java:85]: To be precise, Spotless is not to blame but the Eclipse JDT formatter we have configured it to use.
