### PR TITLE
Fix handling of `CleanupMode.ON_SUCCESS`

### LINKED ISSUE #4464: `@TempDir` directories of successful tests are not cleaned with `ON_SUCCESS` mode
In our test suite we’ve noticed that if any test fails (for whatever reason), then a lot of subsequent tests fail due to out-of-disk problems. This disk space is taken by temporary JUnit directories ([`org.junit.jupiter.api.io.TempDir`](https://github.com/junit-team/junit5/blob/main/junit-jupiter-api/src/main/java/org/junit/jupiter/api/io/TempDir.java)). We use `junit.jupiter.tempdir.cleanup.mode.default=ON_SUCCESS` property, so theoretically only directories for failed tests should be preserved, but we also see many directories for successful ones.

### Expected behavior

All temporary directories of successful tests should be deleted. It worked this way in `5.10.0`.

### Actual behavior

If one test fails, then temporary directories of subsequent successful tests are preserved. First observed in `5.10.1`.

I think it was introduced in https://github.com/junit-team/junit5/issues/3510 . Looks like [`selfOrChildFailed`](https://github.com/junit-team/junit5/blob/c83bfbc7e2739baae273051de79473b2e3ed640c/junit-jupiter-engine/src/main/java/org/junit/jupiter/engine/extension/TempDirectory.java#L330-L335) starts treating all subsequent tests as failed.

## Steps to reproduce

I’ve put a minimal reproducible example in this repository: https://github.com/msulima/junit-tmpdir-cleanup

## Context

 - JUnit: 5.10.1, 5.11.0, 5.12.1
 - Maven 3.9.9 + surefire 3.3.0

### PR DESCRIPTION
**Pull request by marcphilipp**
## Overview

- **Add 5.12.2 release notes from template**
- **Fix handling of `CleanupMode.ON_SUCCESS`**

Fixes #4464.

---

I hereby agree to the terms of the [JUnit Contributor License Agreement](https://github.com/junit-team/junit5/blob/002a0052926ddee57cf90580fa49bc37e5a72427/CONTRIBUTING.md#junit-contributor-license-agreement).

---

### Definition of Done

- [x] There are no TODOs left in the code
- [x] Method [preconditions](https://junit.org/junit5/docs/snapshot/api/org.junit.platform.commons/org/junit/platform/commons/util/Preconditions.html) are checked and documented in the method's Javadoc
- [x] [Coding conventions](https://github.com/junit-team/junit5/blob/HEAD/CONTRIBUTING.md#coding-conventions) (e.g. for logging) have been followed
- [x] Change is covered by [automated tests](https://github.com/junit-team/junit5/blob/HEAD/CONTRIBUTING.md#tests) including corner cases, errors, and exception handling
- [x] Public API has [Javadoc](https://github.com/junit-team/junit5/blob/HEAD/CONTRIBUTING.md#javadoc) and [`@API` annotations](https://apiguardian-team.github.io/apiguardian/docs/current/api/org/apiguardian/api/API.html)
- [x] Change is documented in the [User Guide](https://junit.org/junit5/docs/snapshot/user-guide/) and [Release Notes](https://junit.org/junit5/docs/snapshot/user-guide/#release-notes)

### CODE REVIEW

File: junit-jupiter-engine/src/main/java/org/junit/jupiter/engine/extension/TempDirectory.java [hunk 1]
```diff
@@ -286,7 +291,11 @@ static CloseablePath createTempDir(TempDirFactory factory, CleanupMode cleanupMo
 
 	private static boolean selfOrChildFailed(ExtensionContext context) {
 		return context.getExecutionException().isPresent() //
-				|| context.getStore(NAMESPACE).getOrDefault(CHILD_FAILED, Boolean.class, false);
+				|| getContextSpecificStore(context).getOrDefault(CHILD_FAILED, Boolean.class, false);
+	}
+
+	private static ExtensionContext.Store getContextSpecificStore(ExtensionContext context) {
+		return context.getStore(NAMESPACE.append(context));
```
Comment (marcphilipp) [inline junit-jupiter-engine/src/main/java/org/junit/jupiter/engine/extension/TempDirectory.java:298]: :speech_balloon: This is the important bit: by including the context in the namespace, we prevent it from looking up the key on the parent

File: junit-jupiter-engine/src/main/java/org/junit/jupiter/engine/extension/TempDirectory.java [hunk 2]
```diff
@@ -129,12 +129,17 @@ public void beforeEach(ExtensionContext context) {
...
 
 	private static void installFailureTracker(ExtensionContext context) {
-		context.getStore(NAMESPACE).put(FAILURE_TRACKER, (CloseableResource) () -> context.getParent() //
-				.ifPresent(parentContext -> {
-					if (selfOrChildFailed(context)) {
-						parentContext.getStore(NAMESPACE).put(CHILD_FAILED, true);
-					}
-				}));
+		context.getParent() //
+				.filter(parentContext -> !context.getRoot().equals(parentContext)) //
```
Comment (marcphilipp) [inline junit-jupiter-engine/src/main/java/org/junit/jupiter/engine/extension/TempDirectory.java:133]: :speech_balloon: This line is just an optimization because there never are temp dirs on the engine level so we don't need to store the information there because it will never be read.

Comment (sormuras) [reply junit-jupiter-engine/src/main/java/org/junit/jupiter/engine/extension/TempDirectory.java:133]: Unrelated and potentially breaking - but should be okay.

File: junit-jupiter-engine/src/main/java/org/junit/jupiter/engine/extension/TempDirectory.java (hunk 1 above)
Comment (sormuras) [reply junit-jupiter-engine/src/main/java/org/junit/jupiter/engine/extension/TempDirectory.java:298]: Sounds reasonable.

**Review by sormuras — APPROVED** [review]
Implementation and new test cases look good.
