### PR TITLE
Fix stack overflow error in assertIterableEquals

### LINKED ISSUE #2157: Assertions.assertIterableEquals overflows the stack
## Steps to reproduce

The following code:
```java
var expected = List.of(Path.of("1"));
var actual = List.of(Path.of("1"));
System.out.println(expected);
System.out.println(actual);
assertIterableEquals(expected, actual);
```

Yields:
```
[1]
[1]
java.lang.StackOverflowError
	at java.base/java.util.ArrayList.grow(ArrayList.java:243)
	at java.base/java.util.ArrayList.add(ArrayList.java:453)
	at java.base/java.util.ArrayList.add(ArrayList.java:466)
	at java.base/sun.nio.fs.WindowsPath.initOffsets(WindowsPath.java:649)
	at java.base/sun.nio.fs.WindowsPath.getNameCount(WindowsPath.java:660)
	at java.base/java.nio.file.Path$1.hasNext(Path.java:923)
	at org.junit.jupiter.api.AssertIterableEquals.assertIterableEquals(AssertIterableEquals.java:62)
	at org.junit.jupiter.api.AssertIterableEquals.assertIterableElementsEqual(AssertIterableEquals.java:82)
	at org.junit.jupiter.api.AssertIterableEquals.assertIterableEquals(AssertIterableEquals.java:72)
	at org.junit.jupiter.api.AssertIterableEquals.assertIterableElementsEqual(AssertIterableEquals.java:82)
	at org.junit.jupiter.api.AssertIterableEquals.assertIterableEquals(AssertIterableEquals.java:72)
	[...]
```

## Deliverables

- [ ] Provide fix and test for comparing `Iterable<? extends Iterable<?>>` instances.

### PR DESCRIPTION
**Pull request by sormuras**
## Overview
Prior to this commit an iterable of iterables (here instances of java.nio.file.Path) passed to method `assertIterableEquals` in class `Assertions` of the JUnit Jupiter API yielded a `StackOverflowError`.

This commit prevent the eternal while-loop by leveraging the `equals()`-implementation of the non-null expected element.

Fixes #2157

---

I hereby agree to the terms of the [JUnit Contributor License Agreement](https://github.com/junit-team/junit5/blob/002a0052926ddee57cf90580fa49bc37e5a72427/CONTRIBUTING.md#junit-contributor-license-agreement).

---

### Definition of Done

- [ ] There are no TODOs left in the code
- [ ] Method [preconditions](https://junit.org/junit5/docs/snapshot/api/org/junit/platform/commons/util/Preconditions.html) are checked and documented in the method's Javadoc
- [ ] [Coding conventions](https://github.com/junit-team/junit5/blob/master/CONTRIBUTING.md#coding-conventions) (e.g. for logging) have been followed
- [ ] Change is covered by [automated tests](https://github.com/junit-team/junit5/blob/master/CONTRIBUTING.md#tests) including corner cases, errors, and exception handling
- [ ] Public API has [Javadoc](https://github.com/junit-team/junit5/blob/master/CONTRIBUTING.md#javadoc) and [`@API` annotations](https://apiguardian-team.github.io/apiguardian/docs/current/api/org/apiguardian/api/API.html)
- [ ] Change is documented in the [User Guide](https://junit.org/junit5/docs/snapshot/user-guide/) and [Release Notes](https://junit.org/junit5/docs/snapshot/user-guide/#release-notes)
- [ ] All [continuous integration builds](https://github.com/junit-team/junit5#continuous-integration-builds) pass

### CODE REVIEW

File: junit-jupiter-api/src/main/java/org/junit/jupiter/api/AssertIterableEquals.java [hunk 1]
```diff
@@ -67,6 +67,11 @@ private static void assertIterableEquals(Iterable<?> expected, Iterable<?> actua
 			if (expectedElement == actualElement) {
 				continue;
 			}
+			// Prevent stack overflow error.
+			// See https://github.com/junit-team/junit5/issues/2157 for details.
+			if (expectedElement != null && expectedElement.equals(actualElement)) {
```
Comment (marcphilipp) [inline junit-jupiter-api/src/main/java/org/junit/jupiter/api/AssertIterableEquals.java]:
```suggestion
			if (Objects.equals(expectedElement, actualElement)) {
```

You can then also merge the two `if`s into one because `Objects.equals()` already checks for `==`.

Comment (sormuras) [reply junit-jupiter-api/src/main/java/org/junit/jupiter/api/AssertIterableEquals.java]: Neat improvement.

**Comment by sormuras** [comment]
😱 _Nobody ever uses that assertion in the wild?!_
