### PR TITLE
Ignore Kotlin compiler-generated `DefaultImpls` classes

### LINKED ISSUE #4675: Discovery issue incorrectly reported for Kotlin interfaces
> Hello 👋 I just tested 1.13.2 and DiscoveryIssueNotifier is flooding me with warnings for my Kotlin setup for contract testing (that works perfectly fine - there are no discovery issues). Is it possible to fix it too or provide possibility to disable this new discovery feature?
> 
> Pseudocode example:
> ```kotlin
> interface DatabaseContract {
>     val database: Database
>     
>     @Test
>     fun `should save in batch`() {
>         ...
>     }
> 
>     @Test
>     fun `should read all`() {
>         ...
>     }
> }
> 
> class InMemoryDatabaseTest: DatabaseContract {
>     override val database = InMemoryDatabase()
> }
> 
> class PostgresDatabaseTest: DatabaseContract {
>     override val database = PostgresDatabase()
> }
> ``` 

 _Originally posted by @hektorKS in [#4635](https://github.com/junit-team/junit-framework/issues/4635#issuecomment-3000880679)_

### PR DESCRIPTION
**Pull request by marcphilipp**
## Overview

Resolves #4675.

---

I hereby agree to the terms of the [JUnit Contributor License Agreement](https://github.com/junit-team/junit-framework/blob/002a0052926ddee57cf90580fa49bc37e5a72427/CONTRIBUTING.md#junit-contributor-license-agreement).

---

### Definition of Done

- [x] There are no TODOs left in the code
- [x] Method [preconditions](https://docs.junit.org/snapshot/api/org.junit.platform.commons/org/junit/platform/commons/util/Preconditions.html) are checked and documented in the method's Javadoc
- [x] [Coding conventions](https://github.com/junit-team/junit-framework/blob/HEAD/CONTRIBUTING.md#coding-conventions) (e.g. for logging) have been followed
- [x] Change is covered by [automated tests](https://github.com/junit-team/junit-framework/blob/HEAD/CONTRIBUTING.md#tests) including corner cases, errors, and exception handling
- [x] Public API has [Javadoc](https://github.com/junit-team/junit-framework/blob/HEAD/CONTRIBUTING.md#javadoc) and [`@API` annotations](https://apiguardian-team.github.io/apiguardian/docs/current/api/org/apiguardian/api/API.html)
- [x] Change is documented in the [User Guide](https://docs.junit.org/snapshot/user-guide/) and [Release Notes](https://docs.junit.org/snapshot/user-guide/#release-notes)

### CODE REVIEW

File: junit-platform-commons/src/main/java/org/junit/platform/commons/util/KotlinReflectionUtils.java [hunk 1]
```diff
@@ -11,12 +11,16 @@
 package org.junit.platform.commons.util;
 
 import static org.apiguardian.api.API.Status.INTERNAL;
+import static org.junit.platform.commons.support.ReflectionSupport.findMethod;
```
Comment (sbrannen) [inline junit-platform-commons/src/main/java/org/junit/platform/commons/util/KotlinReflectionUtils.java]: Within the `util` package we shouldn't be importing types from the `support` package -- right?

Comment (marcphilipp) [reply junit-platform-commons/src/main/java/org/junit/platform/commons/util/KotlinReflectionUtils.java]: Changed to `ReflectionUtils` in a4a92673544c75f9617b490dca8d9aab323c2d75

File: junit-platform-commons/src/main/java/org/junit/platform/commons/util/KotlinReflectionUtils.java [hunk 2]
```diff
@@ -65,6 +74,44 @@ public static boolean isKotlinSuspendingFunction(Method method) {
...
+		return false;
+	}
+
+	private static boolean isCompilerGeneratedDefaultMethod(Method method, Class<?> enclosingClass) {
+		if (isStatic(method) && method.getParameterCount() > 0) {
+			var parameterTypes = method.getParameterTypes();
+			if (parameterTypes[0] == enclosingClass) {
+				var originalParameterTypes = parameterTypes.length == 1 //
+						? EMPTY_CLASS_ARRAY //
+						: Arrays.stream(parameterTypes).skip(1).toArray(Class[]::new);
```
Comment (sbrannen) [inline junit-platform-commons/src/main/java/org/junit/platform/commons/util/KotlinReflectionUtils.java]: For use cases like this one, I'd typically go with `System.arraycopy()` instead of a `Stream`.

File: jupiter-tests/src/test/java/org/junit/jupiter/engine/discovery/DiscoveryTests.java [hunk 3]
```diff
@@ -44,9 +44,13 @@
 import org.junit.jupiter.engine.descriptor.ClassTestDescriptor;
 import org.junit.jupiter.engine.descriptor.NestedClassTestDescriptor;
 import org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor;
+import org.junit.jupiter.engine.kotlin.KotlinDefaultImplsTestCase;
+import org.junit.jupiter.engine.kotlin.KotlinInterfaceImplementationTestCase;
+import org.junit.jupiter.engine.kotlin.KotlinInterfaceTestCase;
```
Comment (sbrannen) [inline jupiter-tests/src/test/java/org/junit/jupiter/engine/discovery/DiscoveryTests.java]: I'm pretty sure this will fail in Eclipse.

So, I'll likely have to revise these tests to use reflection once it's on `main`.

File: junit-platform-commons/src/main/java/org/junit/platform/commons/util/KotlinReflectionUtils.java (hunk 2 above)
Comment (marcphilipp) [reply junit-platform-commons/src/main/java/org/junit/platform/commons/util/KotlinReflectionUtils.java]: Refactored in 74d8da3fb42c5dc8115d4c2d05bdad968e53e3ee

File: jupiter-tests/src/test/java/org/junit/jupiter/engine/discovery/DiscoveryTests.java (hunk 3 above)
Comment (marcphilipp) [reply jupiter-tests/src/test/java/org/junit/jupiter/engine/discovery/DiscoveryTests.java]: We do something similar in `TestInstanceLifecycleKotlinTests`. Does that work in Eclipse?

Comment (sbrannen) [reply jupiter-tests/src/test/java/org/junit/jupiter/engine/discovery/DiscoveryTests.java]: If you mean the following, yes that "works".

https://github.com/junit-team/junit-framework/blob/9a6b0a7110396ad04fe342723f5ed9c8a235df8d/jupiter-tests/jupiter-tests.gradle.kts#L51-L55

Comment (sbrannen) [reply jupiter-tests/src/test/java/org/junit/jupiter/engine/discovery/DiscoveryTests.java]: But I was actually thinking about something like the following, so that the rest of the tests still run in Eclipse.

https://github.com/junit-team/junit-framework/blob/9a6b0a7110396ad04fe342723f5ed9c8a235df8d/junit-vintage-engine/src/test/java/org/junit/vintage/engine/VintageTestEngineExecutionTests.java#L867-L872

Comment (marcphilipp) [reply jupiter-tests/src/test/java/org/junit/jupiter/engine/discovery/DiscoveryTests.java]: Done in 8f58fc1e5e9e53c65108569f792016cd49552ed9 and 40ab389fbcd4063c59ab61d9b600c47cce52c8dc

Comment (sbrannen) [reply jupiter-tests/src/test/java/org/junit/jupiter/engine/discovery/DiscoveryTests.java]: Thanks for introducing `@DisabledInEclipse`.

I had already considered doing that but just hadn't gotten around to it. 👍

File: junit-jupiter-api/src/testFixtures/java/org/junit/jupiter/api/extension/DisabledInEclipse.java [hunk 4]
```diff
@@ -0,0 +1,28 @@
...
+import org.junit.jupiter.api.condition.DisabledIf;
+
+/**
+ * @see org.junit.platform.commons.test.IdeUtils#runningInEclipse()
+ */
+@Retention(RetentionPolicy.RUNTIME)
+@Target({ ElementType.TYPE, ElementType.METHOD })
+@DisabledIf("org.junit.platform.commons.test.IdeUtils#runningInEclipse()")
+public @interface DisabledInEclipse {
+	String reason() default "";
```
Comment (sbrannen) [inline junit-jupiter-api/src/testFixtures/java/org/junit/jupiter/api/extension/DisabledInEclipse.java]:
```suggestion
	String value() default "";
```

File: jupiter-tests/src/test/java/org/junit/jupiter/engine/extension/TimeoutInvocationFactoryTests.java [hunk 5]
```diff
@@ -35,9 +35,7 @@
 // Mockito cannot mock this class: class org.junit.jupiter.engine.execution.NamespaceAwareStore.
 // You are seeing this disclaimer because Mockito is configured to create inlined mocks.
 // Byte Buddy could not instrument all classes within the mock's type hierarchy.
-@DisabledIf(//
-		value = "org.junit.platform.commons.test.IdeUtils#runningInEclipse()", //
-		disabledReason = "Mockito cannot create a spy for NamespaceAwareStore using the inline MockMaker in Eclipse IDE")
+@DisabledInEclipse(reason = "Mockito cannot create a spy for NamespaceAwareStore using the inline MockMaker in Eclipse IDE")
```
Comment (sbrannen) [inline jupiter-tests/src/test/java/org/junit/jupiter/engine/extension/TimeoutInvocationFactoryTests.java]:
```suggestion
@DisabledInEclipse("Mockito cannot create a spy for NamespaceAwareStore using the inline MockMaker in Eclipse IDE")
```

**Review by sbrannen — APPROVED** [review]
I think this looks good now. 👍 

Thanks for making all of the changes.

Though, I have not actually tested it in Eclipse yet.

If you'd like me to confirm the behavior in Eclipse before you merge, just let me know, and I'll find time to do so.

Otherwise, I'll confirm after you merge.
