### PR TITLE
Prune stack traces produced by failing tests

### LINKED ISSUE #3247: Prune stack traces produced by failing tests
When a test fails, the outcome is a big stack trace containing a lot of internal JUnit/Java calls.
Since this is rarely interesting for the end user, we should prune this to keep only relevant assertion messages.

See [related post](https://stackoverflow.com/questions/73231944/junit-tests-in-idea-how-to-trim-a-stack-trace) found by @sormuras on Stackoverflow.

## Deliverables

This pruning mechanism should:
- [ ] be an opt-out feature that can be disabled via a system property or configuration parameter
- [ ] prune elements coming from `org.junit` and `java` packages by default (with the exception of Jupiter `Assertions` and `Assumptions` calls)
- [ ] prune all elements prior to and including the first JUnit Launcher call
- [ ] optionally prune additional elements, based on another configuration parameter providing a list of fully qualified class name patterns (using the same syntax as `junit.platform.execution.listeners.deactivate` property)

### PR DESCRIPTION
**Pull request by juliette-derancourt**
Resolves #3247

Co-authored-by: Christian Stein <sormuras@gmail.com>

---

I hereby agree to the terms of the [JUnit Contributor License Agreement](https://github.com/junit-team/junit5/blob/002a0052926ddee57cf90580fa49bc37e5a72427/CONTRIBUTING.md#junit-contributor-license-agreement).

---

### Definition of Done

- [x] There are no TODOs left in the code
- [x] Method [preconditions](https://junit.org/junit5/docs/snapshot/api/org.junit.platform.commons/org/junit/platform/commons/util/Preconditions.html) are checked and documented in the method's Javadoc
- [x] [Coding conventions](https://github.com/junit-team/junit5/blob/HEAD/CONTRIBUTING.md#coding-conventions) (e.g. for logging) have been followed
- [x] Change is covered by [automated tests](https://github.com/junit-team/junit5/blob/HEAD/CONTRIBUTING.md#tests) including corner cases, errors, and exception handling
- [x] Public API has [Javadoc](https://github.com/junit-team/junit5/blob/HEAD/CONTRIBUTING.md#javadoc) and [`@API` annotations](https://apiguardian-team.github.io/apiguardian/docs/current/api/org/apiguardian/api/API.html)
- [x] Change is documented in the [User Guide](https://junit.org/junit5/docs/snapshot/user-guide/) and [Release Notes](https://junit.org/junit5/docs/snapshot/user-guide/#release-notes)

### CODE REVIEW

File: junit-platform-commons/src/main/java/org/junit/platform/commons/util/ExceptionUtils.java [hunk 1]
```diff
@@ -80,4 +94,77 @@ public static String readStackTrace(Throwable throwable) {
...
+	 * @param rootThrowable the {@code Throwable} to explore; never {@code null}
+	 * @return an immutable list of all throwables found, including the supplied
+	 * one; never {@code null}
+	 *
+	 * @since 5.10
+	 */
+	public static List<Throwable> findNestedThrowables(Throwable rootThrowable) {
+		Preconditions.notNull(rootThrowable, "Throwable must not be null");
+
+		HashSet<Throwable> visited = new HashSet<>();
```
Comment (marcphilipp) [inline junit-platform-commons/src/main/java/org/junit/platform/commons/util/ExceptionUtils.java:151]: Preserving the order is not necessary for our use case but might make is easier to debug and reason about the code.

```suggestion
		Set<Throwable> visited = new LinkedHashSet<>();
```

File: junit-platform-commons/src/main/java/org/junit/platform/commons/util/ExceptionUtils.java [hunk 2]
```diff
@@ -80,4 +94,77 @@ public static String readStackTrace(Throwable throwable) {
...
+	 * Find all causes and suppressed exceptions in the backtrace of the
+	 * supplied {@link Throwable}.
+	 *
+	 * @param rootThrowable the {@code Throwable} to explore; never {@code null}
+	 * @return an immutable list of all throwables found, including the supplied
+	 * one; never {@code null}
+	 *
+	 * @since 5.10
+	 */
+	public static List<Throwable> findNestedThrowables(Throwable rootThrowable) {
```
Comment (marcphilipp) [inline junit-platform-commons/src/main/java/org/junit/platform/commons/util/ExceptionUtils.java:148]:
```suggestion
	@API(status = INTERNAL, since = "1.10")
	public static List<Throwable> findNestedThrowables(Throwable rootThrowable) {
```

File: junit-platform-commons/src/main/java/org/junit/platform/commons/util/ExceptionUtils.java [hunk 3]
```diff
@@ -80,4 +94,77 @@ public static String readStackTrace(Throwable throwable) {
...
+	 * JUnit Launcher call will be removed.
+	 *
+	 * @param throwable the {@code Throwable} whose stack trace should be
+	 * pruned; never {@code null}
+	 * @param stackTraceElementFilter the {@code Predicate} used to filter
+	 * elements of the stack trace; never {@code null}
+	 *
+	 * @since 5.10
+	 */
+	public static void pruneStackTrace(Throwable throwable, Predicate<String> stackTraceElementFilter) {
```
Comment (marcphilipp) [inline junit-platform-commons/src/main/java/org/junit/platform/commons/util/ExceptionUtils.java:114]:
```suggestion
	@API(status = INTERNAL, since = "1.10")
	public static void pruneStackTrace(Throwable throwable, Predicate<String> stackTraceElementFilter) {
```

File: junit-platform-launcher/src/main/java/org/junit/platform/launcher/core/StackTracePruningEngineExecutionListener.java [hunk 4]
```diff
@@ -0,0 +1,55 @@
...
+			Throwable throwable = testExecutionResult.getThrowable().get();
+
+			ExceptionUtils.findNestedThrowables(throwable).forEach(this::pruneStackTrace);
+		}
+		super.executionFinished(testDescriptor, testExecutionResult);
+	}
+
+	private void pruneStackTrace(Throwable throwable) {
+		ExceptionUtils.pruneStackTrace(throwable,
+			ClassNamePatternFilterUtils.excludeMatchingClassNames(pruningPattern));
```
Comment (marcphilipp) [inline junit-platform-launcher/src/main/java/org/junit/platform/launcher/core/StackTracePruningEngineExecutionListener.java:52]: I think we should create the `Predicate` in the constructor so it can be reused here rather than compiling `Patterns` for every `Throwable`.

File: junit-platform-launcher/src/main/java/org/junit/platform/launcher/core/StackTracePruningEngineExecutionListener.java [hunk 5]
```diff
@@ -0,0 +1,55 @@
...
+ * Prunes the stack trace in case of a failed event.
+ *
+ * @since 1.10
+ * @see org.junit.platform.commons.util.ExceptionUtils#pruneStackTrace(Throwable, Predicate)
+ */
+class StackTracePruningEngineExecutionListener extends DelegatingEngineExecutionListener {
+
+	public static final String STACKTRACE_PRUNING_ENABLED_PROPERTY_NAME = "junit.platform.stacktrace.pruning.enabled";
+	public static final String STACKTRACE_PRUNING_PATTERN_PROPERTY_NAME = "junit.platform.stacktrace.pruning.pattern";
+	public static final String STACKTRACE_PRUNING_DEFAULT_PATTERN = "org.junit.*,java.*";
```
Comment (marcphilipp) [inline junit-platform-launcher/src/main/java/org/junit/platform/launcher/core/StackTracePruningEngineExecutionListener.java:31]: Corresponding constants should be added in `LauncherConstants` with Javadoc.

File: documentation/src/docs/asciidoc/release-notes/release-notes-5.10.0-M1.adoc [hunk 6]
```diff
@@ -56,6 +56,10 @@ repository on GitHub.
   test engines and their extensions.
 * New dry-run mode to simulate test execution without actually running tests. Please refer
   to the <<../user-guide/index.adoc#launcher-api-dry-run-mode, User Guide>> for details.
+* Stack traces produced by failing tests are now pruned of calls from JUnit and Java by
+  default. This feature can be disabled via the `junit.platform.stacktrace.pruning.enabled`
+  configuration parameter, or configured to exclude other fully qualified class names
+  by providing a list of patterns to `junit.platform.stacktrace.pruning.pattern`.
```
Comment (marcphilipp) [inline documentation/src/docs/asciidoc/release-notes/release-notes-5.10.0-M1.adoc:62]: I think we should also mention this in the User Guide as a new section under "4. Running Tests".

File: junit-platform-commons/src/main/java/org/junit/platform/commons/util/ExceptionUtils.java [hunk 7]
```diff
@@ -31,6 +39,12 @@
 @API(status = INTERNAL, since = "1.0")
 public final class ExceptionUtils {
 
+	private static final String JUNIT_PLATFORM_LAUNCHER_PACKAGE_PREFIX = "org.junit.platform.launcher.";
+	private static final List<String> ALWAYS_INCLUDED_STACK_TRACE_ELEMENTS = Arrays.asList( //
+		"org.junit.jupiter.api.Assertions", //
+		"org.junit.jupiter.api.Assumptions" //
+	);
```
Comment (marcphilipp) [inline junit-platform-commons/src/main/java/org/junit/platform/commons/util/ExceptionUtils.java:46]: Since these are Jupiter-specific, I think they should be passed in to `pruneStackTrace` or be checked in the already passed in `stackTraceElementFilter`.

File: junit-platform-launcher/src/main/java/org/junit/platform/launcher/core/StackTracePruningEngineExecutionListener.java (hunk 5 above)
Comment (marcphilipp) [inline junit-platform-launcher/src/main/java/org/junit/platform/launcher/core/StackTracePruningEngineExecutionListener.java:31]: I think we should also exclude `jdk.internal` etc.

```suggestion
	public static final String STACKTRACE_PRUNING_DEFAULT_PATTERN = "org.junit.*,java.*,jdk.*";
```

File: junit-platform-launcher/src/main/java/org/junit/platform/launcher/core/StackTracePruningEngineExecutionListener.java [hunk 8]
```diff
@@ -0,0 +1,55 @@
...
+
+	private final String pruningPattern;
+
+	StackTracePruningEngineExecutionListener(EngineExecutionListener delegate, String pruningPattern) {
+		super(delegate);
+		this.pruningPattern = pruningPattern;
+	}
+
+	@Override
+	public void executionFinished(TestDescriptor testDescriptor, TestExecutionResult testExecutionResult) {
```
Comment (marcphilipp) [inline junit-platform-launcher/src/main/java/org/junit/platform/launcher/core/StackTracePruningEngineExecutionListener.java:41]: I wonder if we should also always include the test class(es) by inspecting `TestDescriptor.getSource` for `testDescriptor` and all its ancestors. For every `ClassSource` or `MethodSource`, the corresponding class could be added to the allowlist. That way, we could also enable stack trace pruning for our own tests. Thoughts?

**Review by marcphilipp — CHANGES_REQUESTED** [review]

File: junit-platform-launcher/src/main/java/org/junit/platform/launcher/core/StackTracePruningEngineExecutionListener.java (hunk 8 above)
Comment (juliette-derancourt) [reply junit-platform-launcher/src/main/java/org/junit/platform/launcher/core/StackTracePruningEngineExecutionListener.java:45]: Seems like a good idea! 👍

File: junit-platform-launcher/src/main/java/org/junit/platform/launcher/LauncherConstants.java [hunk 9]
```diff
@@ -164,6 +164,59 @@ public class LauncherConstants {
...
+	 * {@code System} or {@code Dev}.
+	 * <li>{@code org.example.MyClass, org.example.TheirClass}: remove
+	 * elements whose FQCN is exactly {@code org.example.MyClass} or
+	 * {@code org.example.TheirClass}.
+	 * </ul>
+	 *
+	 * @see #STACKTRACE_PRUNING_DEFAULT_PATTERN
+	 */
+	@API(status = EXPERIMENTAL, since = "1.10")
+	public static final String STACKTRACE_PRUNING_PATTERN_PROPERTY_NAME = "junit.platform.stacktrace.pruning.pattern";
```
Comment (juliette-derancourt) [inline junit-platform-launcher/src/main/java/org/junit/platform/launcher/LauncherConstants.java:209]: I'm wondering if this is the right name for this property... since its content is similar to `junit.platform.execution.listeners.deactivate`, maybe it should have a more similar name and end with a verb?
But `junit.platform.stacktrace.pruning.prune` looks ugly 😅
Any suggestions?

File: junit-platform-launcher/src/main/java/org/junit/platform/launcher/LauncherConstants.java [hunk 10]
```diff
@@ -164,6 +164,59 @@ public class LauncherConstants {
 	@API(status = EXPERIMENTAL, since = "1.10")
 	public static final String DRY_RUN_PROPERTY_NAME = "junit.platform.execution.dryRun.enabled";
 
+	/**
+	 * Property name used to enable stack trace pruning.
```
Comment (marcphilipp) [inline junit-platform-launcher/src/main/java/org/junit/platform/launcher/LauncherConstants.java:168]: Reads a bit odd with the sentence below.

```suggestion
	 * Property name used to enable or disable stack trace pruning.
```

File: junit-platform-launcher/src/main/java/org/junit/platform/launcher/LauncherConstants.java (hunk 9 above)
Comment (marcphilipp) [reply junit-platform-launcher/src/main/java/org/junit/platform/launcher/LauncherConstants.java:209]: How about `junit.platform.stacktrace.pruning.exclude`?

**Review by marcphilipp — APPROVED** [review]

File: junit-platform-launcher/src/main/java/org/junit/platform/launcher/LauncherConstants.java (hunk 9 above)
Comment (marcphilipp) [reply junit-platform-launcher/src/main/java/org/junit/platform/launcher/LauncherConstants.java:209]: **Team decision:** Let's stick with `junit.platform.stacktrace.pruning.pattern`.

File: documentation/src/docs/asciidoc/release-notes/release-notes-5.10.0-M1.adoc [hunk 11]
```diff
@@ -56,6 +56,10 @@ repository on GitHub.
   test engines and their extensions.
 * New dry-run mode to simulate test execution without actually running tests. Please refer
   to the <<../user-guide/index.adoc#launcher-api-dry-run-mode, User Guide>> for details.
+* Stack traces produced by failing tests are now pruned of calls from `org.junit`, `java`
+  and `jdk` by default. This feature can be disabled or configured to prune other calls
```
Comment (sbrannen) [inline documentation/src/docs/asciidoc/release-notes/release-notes-5.10.0-M1.adoc:60]:
```suggestion
* Stack traces produced by failing tests are now pruned of calls from the `org.junit`, `java`,
  and `jdk` packages by default. This feature can be disabled or configured to prune other calls
```

File: documentation/src/docs/asciidoc/user-guide/running-tests.adoc [hunk 12]
```diff
@@ -1094,3 +1095,28 @@ https://jdk.java.net/jmc/[JDK Mission Control].
 WARNING: Flight Recorder support is currently an _experimental_ feature. You're invited to
 give it a try and provide feedback to the JUnit team so they can improve and eventually
 <<api-evolution, promote>> this feature.
+
+[[stacktrace-pruning]]
+=== Stack trace pruning
+
+Since version 1.10, the JUnit Platform provides opt-out support for pruning stack traces
+produced by failing tests. This feature can be enabled or disabled via the
+`junit.platform.stacktrace.pruning.enabled` _configuration parameter_.
```
Comment (sbrannen) [inline documentation/src/docs/asciidoc/user-guide/running-tests.adoc:1104]:
```suggestion
Since version 1.10, the JUnit Platform provides built-in support for pruning stack traces
produced by failing tests. This feature can be disabled via the
`junit.platform.stacktrace.pruning.enabled` _configuration parameter_.
```

File: documentation/src/docs/asciidoc/user-guide/running-tests.adoc [hunk 13]
```diff
@@ -1094,3 +1095,28 @@ https://jdk.java.net/jmc/[JDK Mission Control].
...
+
+By default, all calls from `org.junit`, `java` and `jdk` packages are removed from the
```
Comment (sbrannen) [inline documentation/src/docs/asciidoc/user-guide/running-tests.adoc:1106]:
```suggestion
By default, all calls from the `org.junit`, `java`, and `jdk` packages are removed from the
```

File: documentation/src/docs/asciidoc/user-guide/running-tests.adoc [hunk 14]
```diff
@@ -1094,3 +1095,28 @@ https://jdk.java.net/jmc/[JDK Mission Control].
...
+stack trace. You can also configure the JUnit Platform to exclude different or additional
+calls. To do this, provide a pattern for the `junit.platform.stacktrace.pruning.pattern`
+_configuration parameter_ to specify which fully qualified class names should be excluded
+from the stack traces.
+
+In addition, and independently of the provided pattern, all elements prior to and
+including the first JUnit Launcher call will be removed.
```
Comment (sbrannen) [inline documentation/src/docs/asciidoc/user-guide/running-tests.adoc:1113]:
```suggestion
including the first call from the JUnit Platform Launcher will be removed.
```

File: documentation/src/docs/asciidoc/user-guide/running-tests.adoc [hunk 15]
```diff
@@ -1094,3 +1095,28 @@ https://jdk.java.net/jmc/[JDK Mission Control].
...
+
+NOTE: Since they provide necessary insides to understand a test failure, calls to
```
Comment (sbrannen) [inline documentation/src/docs/asciidoc/user-guide/running-tests.adoc:1115]:
```suggestion
NOTE: Since they provide necessary insights to understand a test failure, calls to
```

File: junit-platform-commons/src/main/java/org/junit/platform/commons/util/ClassNamePatternFilterUtils.java [hunk 16]
```diff
@@ -50,21 +51,36 @@ private ClassNamePatternFilterUtils() {
 	 * @param patterns a comma-separated list of patterns
 	 */
 	public static <T> Predicate<T> excludeMatchingClasses(String patterns) {
+		return excludeMatchingClasses(patterns, object -> object.getClass().getName());
+	}
+
+	/**
+	 * Create a {@link Predicate} that can be used to exclude (i.e., filter out)
+	 * fully qualified class names matching with any of the supplied patterns.
```
Comment (sbrannen) [inline junit-platform-commons/src/main/java/org/junit/platform/commons/util/ClassNamePatternFilterUtils.java:59]:
```suggestion
	 * fully qualified class names matching any of the supplied patterns.
```

File: junit-platform-launcher/src/main/java/org/junit/platform/launcher/LauncherConstants.java [hunk 17]
```diff
@@ -164,6 +164,59 @@ public class LauncherConstants {
...
+	 * </ul>
+	 *
+	 * @see #STACKTRACE_PRUNING_DEFAULT_PATTERN
+	 */
+	@API(status = EXPERIMENTAL, since = "1.10")
+	public static final String STACKTRACE_PRUNING_PATTERN_PROPERTY_NAME = "junit.platform.stacktrace.pruning.pattern";
+
+	/**
+	 * Default pattern for stack trace pruning which matches {@code org.junit},
+	 * {@code java} and {@code jdk} base packages, and any of their subpackages.
```
Comment (sbrannen) [inline junit-platform-launcher/src/main/java/org/junit/platform/launcher/LauncherConstants.java:213]:
```suggestion
	 * Default pattern for stack trace pruning which matches the {@code org.junit},
	 * {@code java}, and {@code jdk} base packages as well as any of their subpackages.
```

**Review by sbrannen — CHANGES_REQUESTED** [review]
I didn't review the code: I'm leaving that to you, Marc, and Christian for the time being.

I only made a few suggestions for the documentation.

**Review by sormuras — APPROVED** [review]
Looks very good to me.

**Review by sbrannen — APPROVED** [review]
