### PR TITLE
Remove short-circuiting to ensure all classes are checked for cycles

### LINKED ISSUE #4597: `TestClassPredicates.looksLikeIntendedTestClass()` does not consistently detect nested class hierarchy cycles
## Overview

`TestClassPredicatesTests.StandaloneTestClasses.recursiveHierarchies()` currently passes when run with the Gradle build or in IntelliJ IDEA; however, it fails in Eclipse IDE.

Specifically, the assertion on the first line of that test method does not throw an exception in Eclipse.

https://github.com/junit-team/junit5/blob/3c5b457564d559fb0f396d7f303f8effe291daa3/jupiter-tests/src/test/java/org/junit/jupiter/engine/discovery/predicates/TestClassPredicatesTests.java#L221-L224

The reason is twofold:

1. `ReflectionUtils.visitNestedClasses(...)` short-circuits the search algorithm once a `@Nested` test class has been detected.
2. The order in which nested classes are returned from `java.lang.Class.getDeclaredClasses()` apparently differs between the OpenJDK/IntelliJ compilers and the Eclipse compiler.

The result is that `ReflectionUtils.detectInnerClassCycle()` only gets invoked on nested classes until the first `@Nested` class is encountered (or until there are no more nested classes to inspect).

Thus, if a `@Nested` class is detected **before** a nested class with a class hierarchy cycle, the cycle is not detected/reported.

In Eclipse, if you rename `TestClassPredicatesTests.TestCases.OuterClass.InnerClass` to `TestClassPredicatesTests.TestCases.OuterClass.XXXInnerClass`, the test then passes because `TestClassPredicatesTests.TestCases.OuterClass.RecursiveInnerClass` is encountered first, resulting in the expected `JUnitException` stating that it "detected [a] cycle in [the] inner class hierarchy".

## Related Issues

- #242

### PR DESCRIPTION
**Pull request by marcphilipp**
## Overview

Resolves #4597.

---

I hereby agree to the terms of the [JUnit Contributor License Agreement](https://github.com/junit-team/junit5/blob/002a0052926ddee57cf90580fa49bc37e5a72427/CONTRIBUTING.md#junit-contributor-license-agreement).

---

### Definition of Done

- [x] There are no TODOs left in the code
- [x] Method [preconditions](https://junit.org/junit5/docs/snapshot/api/org.junit.platform.commons/org/junit/platform/commons/util/Preconditions.html) are checked and documented in the method's Javadoc
- [x] [Coding conventions](https://github.com/junit-team/junit5/blob/HEAD/CONTRIBUTING.md#coding-conventions) (e.g. for logging) have been followed
- [x] Change is covered by [automated tests](https://github.com/junit-team/junit5/blob/HEAD/CONTRIBUTING.md#tests) including corner cases, errors, and exception handling
- [x] Public API has [Javadoc](https://github.com/junit-team/junit5/blob/HEAD/CONTRIBUTING.md#javadoc) and [`@API` annotations](https://apiguardian-team.github.io/apiguardian/docs/current/api/org/apiguardian/api/API.html)
- [x] Change is documented in the [User Guide](https://junit.org/junit5/docs/snapshot/user-guide/) and [Release Notes](https://junit.org/junit5/docs/snapshot/user-guide/#release-notes)

### CODE REVIEW

File: junit-platform-commons/src/main/java/org/junit/platform/commons/util/ReflectionUtils.java [hunk 1]
```diff
@@ -1144,8 +1142,17 @@ public static boolean isNestedClassPresent(Class<?> clazz, Predicate<Class<?>> p
...
+			boolean foundNestedClass = false;
+			@Override
+			public void accept(Class<?> __) {
+				foundNestedClass = true;
+			}
+		}
+		Tracker tracker = new Tracker();
+
+		visitAllNestedClasses(clazz, predicate, tracker);
+		return tracker.foundNestedClass;
```
Comment (sbrannen) [inline junit-platform-commons/src/main/java/org/junit/platform/commons/util/ReflectionUtils.java:1155]:
```suggestion
		AtomicBoolean found = new AtomicBoolean();
		visitAllNestedClasses(clazz, predicate, __ -> found.set(true));
		return found.get();
```

I think I would prefer that we use an `AtomicBoolean` here for simplicity.

**Review by sbrannen — CHANGES_REQUESTED** [review]
Thanks for putting together this PR at the last minute!

I only requested one minor change.

**Review by sbrannen — APPROVED** [review]

File: junit-platform-commons/src/main/java/org/junit/platform/commons/util/ReflectionUtils.java (hunk 1 above)
Comment (sbrannen) [reply junit-platform-commons/src/main/java/org/junit/platform/commons/util/ReflectionUtils.java]: Ahhh... looks like our comments crossed paths in the ether. 😉
