### PR TITLE
Centralize exit code declaration

### LINKED ISSUE #5051: Documentation for console-launcher seem to miss exit code -1
I go to https://docs.junit.org/current/user-guide/#running-tests-console-launcher and it says:

> The [ConsoleLauncher](https://docs.junit.org/current/api/org.junit.platform.console/org/junit/platform/console/ConsoleLauncher.html) exits with a status code of 1 if any containers or tests failed. If no tests are discovered and the --fail-if-no-tests command-line option is supplied, the ConsoleLauncher exits with a status code of 2. Otherwise, the exit code is 0.

But I found that in case no test-engine is found -1 is returned (or maybe in other cases as well?).

It would be good to know other exits codes as well as I'm currently work on integrate the launcher with another application and want to give good error messages if something fails.

### PR DESCRIPTION
**Pull request by sormuras**
Introduce an internal collection of all status codes returned by the console launcher `ExitCode`. The PR also updated the User Guide to document the current state.

Addresses and closes #5051

---

I hereby agree to the terms of the [JUnit Contributor License Agreement](https://github.com/junit-team/junit-framework/blob/002a0052926ddee57cf90580fa49bc37e5a72427/CONTRIBUTING.md#junit-contributor-license-agreement).

---

### Definition of Done

- [ ] There are no TODOs left in the code
- [ ] Method [preconditions](https://docs.junit.org/snapshot/api/org.junit.platform.commons/org/junit/platform/commons/util/Preconditions.html) are checked and documented in the method's Javadoc
- [ ] [Coding conventions](https://github.com/junit-team/junit-framework/blob/HEAD/CONTRIBUTING.md#coding-conventions) (e.g. for logging) have been followed
- [ ] Change is covered by [automated tests](https://github.com/junit-team/junit-framework/blob/HEAD/CONTRIBUTING.md#tests) including corner cases, errors, and exception handling
- [ ] Public API has [Javadoc](https://github.com/junit-team/junit-framework/blob/HEAD/CONTRIBUTING.md#javadoc) and [`@API` annotations](https://apiguardian-team.github.io/apiguardian/docs/current/api/org/apiguardian/api/API.html)
- [ ] Change is documented in the [User Guide](https://docs.junit.org/snapshot/user-guide/) and [Release Notes](https://docs.junit.org/snapshot/user-guide/#release-notes)

### CODE REVIEW

File: junit-platform-console/src/main/java/org/junit/platform/console/command/ExitCode.java [hunk 1]
```diff
@@ -0,0 +1,49 @@
...
+
+package org.junit.platform.console.command;
+
+import static org.apiguardian.api.API.Status.STABLE;
+
+import org.apiguardian.api.API;
+
+/**
+ * Well-known exit codes of the {@code junit} tool.
+ */
```
Comment (marcphilipp) [inline junit-platform-console/src/main/java/org/junit/platform/console/command/ExitCode.java:17]:
```suggestion
 *
 * @since 6.0.1
 */
```

File: junit-platform-console/src/main/java/org/junit/platform/console/command/ExitCode.java [hunk 2]
```diff
@@ -0,0 +1,49 @@
...
+@API(status = STABLE, since = "6.0.1")
+public final class ExitCode {
```
Comment (marcphilipp) [inline junit-platform-console/src/main/java/org/junit/platform/console/command/ExitCode.java]: Why isn't this class package-private?

```suggestion
final class ExitCode {
```

Comment (sormuras) [reply junit-platform-console/src/main/java/org/junit/platform/console/command/ExitCode.java]: Let's see... I thought that it was accessed by another type residing in a different package.

**Comment by sormuras** [comment]
Ran ´spotlessApply´ on GH Codespaces.

```
[...]
BUILD SUCCESSFUL in 6m 26s
244 actionable tasks: 132 executed, 64 from cache, 48 up-to-date
```
