### PR TITLE
ConsoleLauncher refactoring

### LINKED ISSUE #664: Test tree printer should not continue connection lines past terminal nodes
## Overview

The tree printer continues hierarchy connection lines past terminal nodes as shown below:

```
│  ├─ A stack
│  │  ├─ is instantiated with new Stack() ✔
│  │  ├─ when new
│  │  │  ├─ throws EmptyStackException when popped ✔
│  │  │  ├─ throws EmptyStackException when peeked ✔
│  │  │  ├─ is empty ✔
│  │  │  ├─ after pushing an element
│  │  │  │  ├─ it is no longer empty ✔
│  │  │  │  ├─ returns the element when peeked but remains not empty ✔
│  │  │  │  ├─ returns the element when popped and is empty ✔
```

- (X) **Bug report.** It's conventional to use the lower-left corner character to indicate that a node is the last node in a particular level of the hierarchy.

## Deliverables

- [ ] Detect the last node in a given level of the hierarchy and use the lower-left corner character (extended ASCII 192 or the unicode equivalent) to discontinue the hierarchy's connection line as shown below:

```
│  ├─ A stack
│  │  ├─ is instantiated with new Stack() ✔
│  │  └─ when new
│  │      ├─ throws EmptyStackException when popped ✔
│  │      ├─ throws EmptyStackException when peeked ✔
│  │      ├─ is empty ✔
│  │      └─ after pushing an element
│  │          ├─ it is no longer empty ✔
│  │          ├─ returns the element when peeked but remains not empty ✔
│  │          └─ returns the element when popped and is empty ✔
```

### PR DESCRIPTION
**Pull request by sormuras**
## Overview

This PR refactors some internal and output related behaviours of the `ConsoleLauncher` and the associated `TreePrintingListener`.

- The level of abstraction was lowered within `ConsoleLauncher` and support classes, `ConsoleTask` interface was removed entirely, the correct `Charset` is now properly stored and used.

- Add new command line option `--details-theme` selecting an output details tree theme for when tests are executed. See `org.junit.platform.console.options.Theme` for available themes.

- `TreePrintingListener` now buffers all events in order to emit status results of containers and render nicer tree branches that indicate the last test of a container with a closing tile, which fixes #664  and produces trees like:

	 ├─ engine alpha ✔
	 │  └─ container 1 ✔
	 │     └─ test 01 ✔
	 └─ engine omega ✔
	    ├─ container 2 ✔
	    │  └─ test 11 ■ aborted
	    └─ container 3 ✔
	       ├─ skipped ↷ because
	       └─ failing ✘ BäMM

- An integration platform test named `ConsoleDetailsTest` asserting all combinations of console outputs _"test result **x** details mode **x** theme"_ ensures the expected overall behaviour of the `ConsoleLauncher`. See `platform-tests/src/test/resources/console/details/**/*out.txt` files.

---
I hereby agree to the terms of the JUnit Contributor License Agreement.
---

### Definition of Done

- [x] There are no TODOs left in the code
- [x] Method [preconditions](http://junit.org/junit5/docs/snapshot/api/org/junit/platform/commons/util/Preconditions.html) are checked and documented in the method's Javadoc
- [x] [Coding conventions](https://github.com/junit-team/junit5/blob/master/CONTRIBUTING.md#coding-conventions) (e.g. for logging) have been followed
- [x] Change is covered by [automated tests](https://github.com/junit-team/junit5/blob/master/CONTRIBUTING.md#tests)
- [x] Public API has [Javadoc](https://github.com/junit-team/junit5/blob/master/CONTRIBUTING.md#javadoc) and [`@API` annotations](http://junit.org/junit5/docs/snapshot/api/org/junit/platform/commons/meta/API.html)
- [x] Change is documented in the [User Guide](http://junit.org/junit5/docs/snapshot/user-guide/) and [Release Notes](http://junit.org/junit5/docs/snapshot/user-guide/#release-notes)
- [x] All [continuous integration builds](https://github.com/junit-team/junit5#continuous-integration-builds) pass

### CODE REVIEW

File: junit-platform-commons/src/main/java/org/junit/platform/commons/util/AnnotationUtils.java [hunk 1]
```diff
@@ -228,7 +228,7 @@ else if (candidate.annotationType().equals(containerType)) {
 					// Note: it's not a legitimate container annotation if it doesn't declare
 					// a 'value' attribute that returns an array of the contained annotation type.
 					// Thus we proceed without verifying this assumption.
-					Method method = ReflectionUtils.getMethod(containerType, "value").get();
+					Method method = ReflectionUtils.getMethod(containerType, "value").orElseThrow(AssertionError::new);
```
Comment (gaganis) [inline junit-platform-commons/src/main/java/org/junit/platform/commons/util/AnnotationUtils.java]: Since we are throwing our own exception here instead of the default NoSuchElementException from Optional::get, wouldn't it be better if we added a message detailing the assumption that failed?

something like "container must declare a 'value' attribute"

Comment (sormuras) [inline junit-platform-commons/src/main/java/org/junit/platform/commons/util/AnnotationUtils.java]: Was my first thought, too. But the existance of the `value` annotation attribute is guaranteed by the JLS (looking for the link), that the simple "get()" was already ok here. The "get()" produced a warning marker in the IDE, though, which is eliminated with the use of "orElseThrow(AssertionError::new)".

Comment (gaganis) [inline junit-platform-commons/src/main/java/org/junit/platform/commons/util/AnnotationUtils.java]: Cool then! 
I wasn't aware of that. Thank you for sharing the link!

File: platform-tests/src/test/resources/console/details/report/Report-reportMultiEntriesWithMultiMappings-tree-unicode.out.txt [hunk 2]
```diff
@@ -0,0 +1,26 @@
+╷
+└─ JUnit Jupiter ✔
+   └─ Report ✔
+      └─ reportMultiEntriesWithMultiMappings(TestReporter) ✔
+            ....-..-..T..:...*
+               user name = `dk38`
+               award year = `1974`
+            ....-..-..T..:...* single = `mapping`
+            ....-..-..T..:...*
```
Comment (sormuras) [inline platform-tests/src/test/resources/console/details/report/Report-reportMultiEntriesWithMultiMappings-tree-unicode.out.txt]: How about an optional caption an user can provide to describe an entry set? In pseudo-code:

`TestReporter.publishEntry("user table", Map.of(...));`

which yields:

```
            user table [....-..-..T..:...*]
               user name = dk38
               award year = 1974
```

File: junit-platform-commons/src/main/java/org/junit/platform/commons/util/AnnotationUtils.java [hunk 3]
```diff
@@ -258,6 +258,10 @@ else if (candidate.annotationType().equals(containerType)) {
 		// @formatter:on
 	}
 
+	public static List<Method> findAnnotatedMethods(Class<?> clazz, Class<? extends Annotation> annotationType) {
+		return findAnnotatedMethods(clazz, annotationType, MethodSortOrder.HierarchyDown);
+	}
+
```
Comment (marcphilipp) [inline junit-platform-commons/src/main/java/org/junit/platform/commons/util/AnnotationUtils.java]: I don't think we should set a default for`MethodSortOrder`. That's the caller's responsibility and may lead to subtle bugs. So, I think we should remove this method.

File: junit-platform-commons/src/main/java/org/junit/platform/commons/util/ReflectionUtils.java [hunk 4]
```diff
@@ -400,6 +401,53 @@ public static Object invokeMethod(Method method, Object target, Object... args)
...
+		builder.append(types[0].getName());
+		if (types.length > 1) {
+			for (int i = 1; i < types.length; i++) {
+				builder.append(',');
+				builder.append(types[i].getName());
+			}
+		}
+		builder.append(')');
+		return builder.toString();
+	}
```
Comment (marcphilipp) [inline junit-platform-commons/src/main/java/org/junit/platform/commons/util/ReflectionUtils.java]: Can this method just call `getFullyQualifiedMethodName(method.getDeclaringClass(), method.getName(), method.getParameterTypes())`?

File: junit-platform-console/src/main/java/org/junit/platform/console/options/AvailableOptions.java [hunk 5]
```diff
@@ -84,6 +85,13 @@
 				.withValuesConvertedBy(new DetailsConverter()) //
 				.defaultsTo(CommandLineOptions.DEFAULT_DETAILS);
 
+		theme = parser.accepts("details-theme",
+			"Select an output details tree theme for when tests are executed. Use one of: " + asList(Theme.values())) //
+				.withRequiredArg() //
+				.ofType(Theme.class) //
+				.withValuesConvertedBy(new ThemeConverter()) //
+				.defaultsTo(CommandLineOptions.DEFAULT_THEME);
+
```
Comment (marcphilipp) [inline junit-platform-console/src/main/java/org/junit/platform/console/options/AvailableOptions.java]: Please add a test for this option to `JOptSimpleCommandLineOptionsParserTests`.

File: junit-platform-console/src/main/java/org/junit/platform/console/tasks/TreePrinter.java [hunk 6]
```diff
@@ -0,0 +1,176 @@
...
+	private void printThrowable(String indent, TestExecutionResult result) {
+		if (!result.getThrowable().isPresent()) {
+			return;
+		}
+		Throwable throwable = result.getThrowable().get();
+		printMessage(FAILED, indent, throwable.getMessage());
+		// ...or print entire stacktrace?
+		// out.println();
+		// out.print(indent + color(FAILED, theme.vertical()));
+		// printMessage(FAILED, indent, ExceptionUtils.readStackTrace(throwable));
```
Comment (marcphilipp) [inline junit-platform-console/src/main/java/org/junit/platform/console/tasks/TreePrinter.java]: I see dead code. ☠️

File: junit-platform-console/src/main/java/org/junit/platform/console/tasks/TreePrinter.java [hunk 7]
```diff
@@ -0,0 +1,176 @@
...
+	private void printMessage(Color color, String indent, String message) {
+		String[] lines = message.split("\\R");
+		out.print(" ");
+		out.print(color(color, lines[0]));
+		if (lines.length > 1) {
+			for (int i = 1; i < lines.length; i++) {
+				out.println();
+				out.print(indent);
+				if (StringUtils.isNotBlank(lines[i])) {
+					String extra = theme.blank(); // i + 1 < lines.length ? theme.vertical() : theme.end() + " ";
```
Comment (marcphilipp) [inline junit-platform-console/src/main/java/org/junit/platform/console/tasks/TreePrinter.java]: Why this comment?

File: junit-platform-commons/src/main/java/org/junit/platform/commons/util/AnnotationUtils.java (hunk 3 above)
Comment (sormuras) [inline junit-platform-commons/src/main/java/org/junit/platform/commons/util/AnnotationUtils.java]: I introduced it because there's a similar convenient overload at `ReflectionUtils:611`:
```
public static List<Method> findMethods(Class<?> clazz, Predicate<Method> predicate) {
	return findMethods(clazz, predicate, MethodSortOrder.HierarchyDown);
}
```

File: junit-platform-commons/src/main/java/org/junit/platform/commons/util/ReflectionUtils.java (hunk 4 above)
Comment (sormuras) [inline junit-platform-commons/src/main/java/org/junit/platform/commons/util/ReflectionUtils.java]: Sure.

File: junit-platform-console/src/main/java/org/junit/platform/console/options/AvailableOptions.java (hunk 5 above)
Comment (sormuras) [inline junit-platform-console/src/main/java/org/junit/platform/console/options/AvailableOptions.java]: On my way.

File: junit-platform-console/src/main/java/org/junit/platform/console/tasks/TreePrinter.java (hunk 6 above)
Comment (sormuras) [inline junit-platform-console/src/main/java/org/junit/platform/console/tasks/TreePrinter.java]: Not for much longer...

File: junit-platform-console/src/main/java/org/junit/platform/console/tasks/TreePrinter.java (hunk 7 above)
Comment (sormuras) [inline junit-platform-console/src/main/java/org/junit/platform/console/tasks/TreePrinter.java]: ...dead code, actually. Will be gone.

File: junit-platform-commons/src/main/java/org/junit/platform/commons/util/AnnotationUtils.java (hunk 3 above)
Comment (sormuras) [inline junit-platform-commons/src/main/java/org/junit/platform/commons/util/AnnotationUtils.java]: I removed the new one from `AnnotationUtils` and switched to the one declared in `ReflectionUtils`.
