### PR TITLE
Ignore implicit config params in EngineTestKit by default

### LINKED ISSUE #2285: TestEngineKit by default picks up settings for parallel execution
I was working on [JUnit-pioneer #131](https://github.com/junit-pioneer/junit-pioneer/issues/131), which is about making some extensions thread safe, e.g. due using the `@ResourceLock` annotation.
 
For testing purposes I set the execution to the most parallel execution possible (Test classes and methods inside each class are executed in parallel):

```properties
#  Enable parallel execution of JUnit tests
junit.jupiter.execution.parallel.enabled=true
# Run all tests methods inside a class in parallel as default
junit.jupiter.execution.parallel.mode.default=concurrent
# Run all tests classes in parallel as default
junit.jupiter.execution.parallel.mode.classes.default=concurrent
# Explicit set the execution strategy to dynamic (default strategy)
junit.jupiter.execution.parallel.config.strategy=dynamic
# Explicit set the factor of dynamic strategy to its default value 
junit.jupiter.execution.parallel.config.dynamic.factor=1
```

It seems that by current default the `TestEngineKit` also picks up those settings for parallel execution(_, which results in a large amount of flaky tests, when you verify your tests using the engine kit_).
@marcphilipp thinks this is unexpected, when using EngineTestKit and JUnit should not do this be default. So he [asked](https://github.com/junit-pioneer/junit-pioneer/issues/131#issuecomment-622953047) me to open an issue for further investigation and decision.

Note: He also mentioned that a workaround for the current behavior is so disable the parallel execution at the `TestEngineKit` using `.configurationParameter("junit.jupiter.execution.parallel.enabled", "false")`.

### PR DESCRIPTION
**Pull request by marcphilipp**
Resolves #2285.

---

### Definition of Done

- [x] There are no TODOs left in the code
- [x] Method [preconditions](https://junit.org/junit5/docs/snapshot/api/org/junit/platform/commons/util/Preconditions.html) are checked and documented in the method's Javadoc
- [x] [Coding conventions](https://github.com/junit-team/junit5/blob/master/CONTRIBUTING.md#coding-conventions) (e.g. for logging) have been followed
- [x] Change is covered by [automated tests](https://github.com/junit-team/junit5/blob/master/CONTRIBUTING.md#tests) including corner cases, errors, and exception handling
- [x] Public API has [Javadoc](https://github.com/junit-team/junit5/blob/master/CONTRIBUTING.md#javadoc) and [`@API` annotations](https://apiguardian-team.github.io/apiguardian/docs/current/api/org/apiguardian/api/API.html)
- [x] Change is documented in the [User Guide](https://junit.org/junit5/docs/snapshot/user-guide/) and [Release Notes](https://junit.org/junit5/docs/snapshot/user-guide/#release-notes)
- [x] All [continuous integration builds](https://github.com/junit-team/junit5#continuous-integration-builds) pass

### CODE REVIEW

File: junit-platform-launcher/src/main/java/org/junit/platform/launcher/core/LauncherDiscoveryRequestBuilder.java [hunk 1]
```diff
@@ -225,18 +226,31 @@ else if (filter instanceof DiscoveryFilter<?>) {
 		}
 	}
 
+	@API(status = API.Status.EXPERIMENTAL, since = "1.7")
+	public LauncherDiscoveryRequestBuilder withImplicitConfigurationParameters(
```
Comment (marcphilipp) [inline junit-platform-launcher/src/main/java/org/junit/platform/launcher/core/LauncherDiscoveryRequestBuilder.java:230]:
```suggestion
	public LauncherDiscoveryRequestBuilder enableImplicitConfigurationParameters(
```

File: junit-platform-testkit/src/main/java/org/junit/platform/testkit/engine/EngineTestKit.java [hunk 2]
```diff
@@ -438,6 +439,12 @@ public Builder configurationParameters(Map<String, String> configurationParamete
 			return this;
 		}
 
+		@API(status = API.Status.EXPERIMENTAL, since = "1.7")
+		public Builder withImplicitConfigurationParameters(boolean useImplicitConfigurationParameters) {
```
Comment (marcphilipp) [inline junit-platform-testkit/src/main/java/org/junit/platform/testkit/engine/EngineTestKit.java:443]:
```suggestion
		public Builder enableImplicitConfigurationParameters(boolean enabled) {
```

File: junit-platform-launcher/src/main/java/org/junit/platform/launcher/core/LauncherConfigurationParameters.java [hunk 3]
```diff
@@ -36,25 +38,157 @@
...
+		private Builder() {
+		}
+
+		Builder withExplicitParameters(Map<String, String> parameters) {
+			Preconditions.notNull(parameters, "configuration parameters must not be null");
+			explicitParameters.putAll(parameters);
+			return this;
+		}
+
+		Builder withImplicitLookups(boolean useImplicitLookups) {
```
Comment (marcphilipp) [inline junit-platform-launcher/src/main/java/org/junit/platform/launcher/core/LauncherConfigurationParameters.java:99]:
```suggestion
		Builder enableImplicitLookups(boolean enabled) {
```

File: junit-platform-launcher/src/main/java/org/junit/platform/launcher/core/LauncherConfigurationParameters.java [hunk 4]
```diff
@@ -36,25 +38,157 @@
...
+	static final class Builder {
+
+		private final Map<String, String> explicitParameters = new HashMap<>();
+		private boolean useImplicitLookups = true;
+		private String configFileName = ConfigurationParameters.CONFIG_FILE_NAME;
+
+		private Builder() {
+		}
+
+		Builder withExplicitParameters(Map<String, String> parameters) {
```
Comment (marcphilipp) [inline junit-platform-launcher/src/main/java/org/junit/platform/launcher/core/LauncherConfigurationParameters.java:93]:
```suggestion
		Builder explicitParameters(Map<String, String> parameters) {
```

File: junit-platform-launcher/src/main/java/org/junit/platform/launcher/core/LauncherConfigurationParameters.java [hunk 5]
```diff
@@ -36,25 +38,157 @@
...
+			explicitParameters.putAll(parameters);
+			return this;
+		}
+
+		Builder withImplicitLookups(boolean useImplicitLookups) {
+			this.useImplicitLookups = useImplicitLookups;
+			return this;
+		}
+
+		Builder withConfigFileName(String configFileName) {
```
Comment (marcphilipp) [inline junit-platform-launcher/src/main/java/org/junit/platform/launcher/core/LauncherConfigurationParameters.java:104]:
```suggestion
		Builder configFileName(String configFileName) {
```

File: junit-platform-launcher/src/main/java/org/junit/platform/launcher/core/LauncherConfigurationParameters.java [hunk 6]
```diff
@@ -36,25 +38,157 @@
...
+			if (useImplicitLookups) {
+				lookups.add(Lookup.systemProperties());
+				lookups.add(Lookup.propertiesFile(configFileName));
+			}
+			return new LauncherConfigurationParameters(lookups);
+		}
 	}
 
-	private static Properties fromClasspathResource(String configFileName) {
+	private interface Lookup {
```
Comment (marcphilipp) [inline junit-platform-launcher/src/main/java/org/junit/platform/launcher/core/LauncherConfigurationParameters.java:123]:
```suggestion
	private interface PropertyProvider {
```
