### PR TITLE
URL encode reserved characters in UniqueId segment strings

### LINKED ISSUE #810: UniqueId.parse fails for methods with array type parameters
## Bug description
```
String idString = uniqueIdFromMethodDescriptorWithArrayParameter.toString();
UniqueId id = UniqueId.parse(idString);
```
will fail with `PreconditionViolation` since array types are described with an `[` in front but `[` chars are currently forbidden as segment values.

## Suggested Solution

Change representation of array types in `ReflectionUtils.findMethod(clazz, methodName, parameterTypeNames)` and `StringUtils.nullSafeToString(classes)`. 

Alternative: Don't use `[` as separator char in unique IDs. But some 3rd party tools might already have committed to the current format.

## Deliverables

- [ ] Encode `segmentType` and `value` in constructor and decode in `parse`.

### PR DESCRIPTION
**Pull request by sormuras**
## Overview

Prior to this commit segment strings could contain characters that are used by the toString-representation syntax of UniqueIdFormat. Now these "forbidden" (reserved) characters are URL encoded, as well as decoded when parsing unique ids.

Fixes #810

---

I hereby agree to the terms of the JUnit Contributor License Agreement.

---

### Definition of Done

- [x] There are no TODOs left in the code
- [x] Method [preconditions](http://junit.org/junit5/docs/snapshot/api/org/junit/platform/commons/util/Preconditions.html) are checked and documented in the method's Javadoc
- [x] [Coding conventions](https://github.com/junit-team/junit5/blob/master/CONTRIBUTING.md#coding-conventions) (e.g. for logging) have been followed
- [x] Change is covered by [automated tests](https://github.com/junit-team/junit5/blob/master/CONTRIBUTING.md#tests)
- [x] Public API has [Javadoc](https://github.com/junit-team/junit5/blob/master/CONTRIBUTING.md#javadoc) and [`@API` annotations](http://junit.org/junit5/docs/snapshot/api/org/junit/platform/commons/meta/API.html)
- [x] Change is documented in the [User Guide](http://junit.org/junit5/docs/snapshot/user-guide/) and [Release Notes](http://junit.org/junit5/docs/snapshot/user-guide/#release-notes)
- [x] All [continuous integration builds](https://github.com/junit-team/junit5#continuous-integration-builds) pass

### CODE REVIEW

File: junit-jupiter-engine/src/test/java/org/junit/jupiter/engine/execution/ArrayTests.java [hunk 1]
```diff
@@ -0,0 +1,55 @@
...
+	void executeTestsForPrimitiveArrayMethodInjectionCases() {
+		ExecutionEventRecorder eventRecorder = executeTestsForClass(PrimitiveArrayMethodInjectionTestCase.class);
+
+		assertEquals(1, eventRecorder.getTestStartedCount(), "# tests started");
+		assertEquals(1, eventRecorder.getTestSuccessfulCount(), "# tests succeeded");
+		assertEquals(0, eventRecorder.getTestFailedCount(), "# tests failed");
+
+		eventRecorder.getExecutionEvents().stream().map(ExecutionEvent::getTestDescriptor).distinct().skip(2).map(
+			TestDescriptor::getUniqueId).forEach(id -> UniqueId.parse(id.toString()));
+	}
```
Comment (jbduncan) [inline junit-jupiter-engine/src/test/java/org/junit/jupiter/engine/execution/ArrayTests.java]: The `.forEach(...)` above could probably be expanded to the following code segment (to use method references more consistently).

```java
... .map(UniqueId::toString).forEach(UniqueId::parse);
```

It may also be worth splitting the line `eventRecorder.getExecutionEvents().stream()...` across multiple lines with `@formatter:(off|on)` to improve readability.

But other than those two potential areas for improvement, LGTM. :)
