### PR TITLE
Fix constructor invocation of `Nested` classes on Java versions < 21

### LINKED ISSUE #4417: Nested tests broken with 5.13.0-M1 on Java 17
Nested tests are failing with new milestone version (5.13.0-M1), when running with Java 17.

Output from gradle build:

> 2025-03-22T17:04:12.060+0100 [DEBUG] [TestEventLogger]     org.junit.platform.commons.PreconditionViolationException: First parameter must be implicit
2025-03-22T17:04:12.060+0100 [DEBUG] [TestEventLogger]         at java.base@17.0.2/java.util.Optional.orElseGet(Optional.java:364)
2025-03-22T17:04:12.060+0100 [DEBUG] [TestEventLogger]         at java.base@17.0.2/java.util.ArrayList.forEach(ArrayList.java:1511)
2025-03-22T17:04:12.060+0100 [DEBUG] [TestEventLogger]         at java.base@17.0.2/java.util.ArrayList.forEach(ArrayList.java:1511)
2025-03-22T17:04:12.060+0100 [DEBUG] [TestEventLogger]         at java.base@17.0.2/java.util.ArrayList.forEach(ArrayList.java:1511)

Using Java 21 works fine. Using Java 17 and version 5.12.1 also works.

## Steps to reproduce
Clone samples repo (https://github.com/junit-team/junit5-samples) and switch to `junit5-jupiter-starter-gradle`.

Copy `TestingAStackDemo` from docs (https://junit.org/junit5/docs/current/user-guide/#writing-tests-nested) to  gradle project.

Add toolchain config in `build.gradle`:

```
java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(17)
    }
}
```
Switch to milestone dependency in `build.gradle`:
```
testImplementation(platform('org.junit:junit-bom:5.13.0-M1'))
```
Execute tests: `./gradlew clean test`
## Context

 - Used versions (Jupiter/Vintage/Platform): 5.13.0-M1
 - Build Tool/IDE: Gradle

## Deliverables

- [ ] Remove usages of `Parameter.isImplicit()`

### PR DESCRIPTION
**Pull request by marcphilipp**
## Overview

Fixes #4417.

---

I hereby agree to the terms of the [JUnit Contributor License Agreement](https://github.com/junit-team/junit5/blob/002a0052926ddee57cf90580fa49bc37e5a72427/CONTRIBUTING.md#junit-contributor-license-agreement).

---

### Definition of Done

- [x] There are no TODOs left in the code
- [x] Method [preconditions](https://junit.org/junit5/docs/snapshot/api/org.junit.platform.commons/org/junit/platform/commons/util/Preconditions.html) are checked and documented in the method's Javadoc
- [x] [Coding conventions](https://github.com/junit-team/junit5/blob/HEAD/CONTRIBUTING.md#coding-conventions) (e.g. for logging) have been followed
- [x] Change is covered by [automated tests](https://github.com/junit-team/junit5/blob/HEAD/CONTRIBUTING.md#tests) including corner cases, errors, and exception handling
- [x] Public API has [Javadoc](https://github.com/junit-team/junit5/blob/HEAD/CONTRIBUTING.md#javadoc) and [`@API` annotations](https://apiguardian-team.github.io/apiguardian/docs/current/api/org/apiguardian/api/API.html)
- [x] Change is documented in the [User Guide](https://junit.org/junit5/docs/snapshot/user-guide/) and [Release Notes](https://junit.org/junit5/docs/snapshot/user-guide/#release-notes)

### CODE REVIEW

File: junit-jupiter-engine/src/main/java/org/junit/jupiter/engine/execution/ParameterResolutionUtils.java [hunk 1]
```diff
@@ -99,7 +99,6 @@ public static Object[] resolveParameters(Executable executable, Optional<Object>
 		// Ensure that the outer instance is resolved as the first parameter if
 		// the executable is a constructor for an inner class.
 		if (outerInstance.isPresent()) {
-			Preconditions.condition(parameters[0].isImplicit(), "First parameter must be implicit");
```
Comment (sormuras) [inline junit-jupiter-engine/src/main/java/org/junit/jupiter/engine/execution/ParameterResolutionUtils.java:102]: Instead of deleting this check, wouldn't it be better to also apply the same "isInnerClass(...)" test?

File: junit-jupiter-engine/src/main/java/org/junit/jupiter/engine/execution/ParameterResolutionUtils.java [hunk 2]
```diff
@@ -115,9 +114,6 @@ public static Object[] resolveParameters(Executable executable, Optional<Object>
 	private static Object resolveParameter(ParameterContext parameterContext, Executable executable,
 			ExtensionContextSupplier extensionContext, ExtensionRegistry extensionRegistry) {
 
-		Preconditions.condition(!parameterContext.getParameter().isImplicit(),
```
Comment (sormuras) [inline junit-jupiter-engine/src/main/java/org/junit/jupiter/engine/execution/ParameterResolutionUtils.java:118]: Same here? Replace test with `isInnerClass(...)` check applicable?

**Review by sormuras — APPROVED** [review]

File: junit-jupiter-engine/src/main/java/org/junit/jupiter/engine/execution/ParameterResolutionUtils.java (hunk 1 above)
Comment (marcphilipp) [reply junit-jupiter-engine/src/main/java/org/junit/jupiter/engine/execution/ParameterResolutionUtils.java:102]: That's basically what `outerInstance.isPresent()` does. I only recently added this check when working on parameterized classes.
