### PR TITLE
Revise stacktrace pruning

### LINKED ISSUE #3299: Revise stack trace pruning
## Context

Stack trace pruning was introduced in #3247.
We want this feature to be disabled for tests inside this repository (otherwise all stack traces would be almost empty), and it is when the tests are launched via gradle (due to [this setting](https://github.com/junit-team/junit5/blob/69e74953eacb174842a65a2d7bf67c4d633de6e9/gradle/plugins/common/src/main/kotlin/junitbuild.testing-conventions.gradle.kts#L44)). But when launched in a different way, this setting have no impact and the feature is therefore enabled when it shouldn’t.

## Solution

A potential solution could be to not prune stack traces of tests specifically located inside the `org.junit` package, even when the feature is enabled.

## Related

- https://github.com/junit-team/junit5/pull/3277#discussion_r1181233970

## Deliverables

- [ ] Collect `MethodSource` and `ClassSource` instances from the current test descriptor and its parents, find the bottom-most stackframe with one of these classes, and include all stackframe upward from there
- [ ] Don't prune everything from `java.*` and `jdk.*`, just the reflection packages from both but only below the test method
- [ ] Remove package pattern configuration parameter introduced in M1

### PR DESCRIPTION
**Pull request by juliette-derancourt**
## Overview

Resolves #3299

---

I hereby agree to the terms of the [JUnit Contributor License Agreement](https://github.com/junit-team/junit5/blob/002a0052926ddee57cf90580fa49bc37e5a72427/CONTRIBUTING.md#junit-contributor-license-agreement).

---

### Definition of Done

- [ ] There are no TODOs left in the code
- [ ] Method [preconditions](https://junit.org/junit5/docs/snapshot/api/org.junit.platform.commons/org/junit/platform/commons/util/Preconditions.html) are checked and documented in the method's Javadoc
- [ ] [Coding conventions](https://github.com/junit-team/junit5/blob/HEAD/CONTRIBUTING.md#coding-conventions) (e.g. for logging) have been followed
- [ ] Change is covered by [automated tests](https://github.com/junit-team/junit5/blob/HEAD/CONTRIBUTING.md#tests) including corner cases, errors, and exception handling
- [ ] Public API has [Javadoc](https://github.com/junit-team/junit5/blob/HEAD/CONTRIBUTING.md#javadoc) and [`@API` annotations](https://apiguardian-team.github.io/apiguardian/docs/current/api/org/apiguardian/api/API.html)
- [ ] Change is documented in the [User Guide](https://junit.org/junit5/docs/snapshot/user-guide/) and [Release Notes](https://junit.org/junit5/docs/snapshot/user-guide/#release-notes)

### CODE REVIEW

File: platform-tests/src/test/java/org/junit/platform/commons/util/ExceptionUtilsTests.java [hunk 1]
```diff
@@ -64,15 +67,16 @@ void readStackTraceForLocalJUnitException() {
 		}
 	}
 
-	@Test
-	void pruneStackTraceOfCallsFromSpecificPackage() {
+	@ParameterizedTest
+	@ValueSource(strings = { "org.junit.", "jdk.internal.reflect.", "sun.reflect." })
+	void pruneStackTraceOfCallsFromSpecificPackage(String shouldBePruned) {
```
Comment (sbrannen) [inline platform-tests/src/test/java/org/junit/platform/commons/util/ExceptionUtilsTests.java:72]: Is there a concrete need to throw and catch these exceptions?

If not, just rely on the fact that `fillInStackTrace()` is called by the exceptions constructor (technically in `java.lang.Throwable.Throwable(String)`).

File: platform-tests/src/test/java/org/junit/platform/commons/util/ExceptionUtilsTests.java [hunk 2]
```diff
@@ -64,15 +67,16 @@ void readStackTraceForLocalJUnitException() {
...
 		try {
 			throw new JUnitException("expected");
 		}
 		catch (JUnitException e) {
-			pruneStackTrace(e, element -> !element.startsWith("org.junit."));
+			pruneStackTrace(e, Collections.emptyList());
```
Comment (sbrannen) [inline platform-tests/src/test/java/org/junit/platform/commons/util/ExceptionUtilsTests.java:77]: In tests, feel free to use `List.of()` instead of `Collections.emptyList()`.

**Review by sbrannen — CHANGES_REQUESTED** [review]
I've requested a few minor changes and will hopefully find time to perform a more thorough review after the PR has been updated.

**Review by sbrannen — APPROVED** [review]

File: junit-platform-commons/src/main/java/org/junit/platform/commons/util/ExceptionUtils.java [hunk 3]
```diff
@@ -92,35 +94,44 @@ public static String readStackTrace(Throwable throwable) {
...
 	 */
 	@API(status = INTERNAL, since = "5.10")
-	public static void pruneStackTrace(Throwable throwable, Predicate<String> stackTraceElementFilter) {
+	public static void pruneStackTrace(Throwable throwable, List<String> testClassNames) {
 		Preconditions.notNull(throwable, "Throwable must not be null");
-		Preconditions.notNull(stackTraceElementFilter, "Predicate must not be null");
+		Preconditions.notNull(testClassNames, "List of test class names must not be null");
+
+		Predicate<String> stackTraceElementFilter = ClassNamePatternFilterUtils //
+				.excludeMatchingClassNames(STACK_TRACE_ELEMENTS_TO_EXCLUDE);
```
Comment (marcphilipp) [inline junit-platform-commons/src/main/java/org/junit/platform/commons/util/ExceptionUtils.java:118]: I think we should extract this into a constant.

File: junit-platform-launcher/src/main/java/org/junit/platform/launcher/core/StackTracePruningEngineExecutionListener.java [hunk 4]
```diff
@@ -10,49 +10,60 @@
...
+			ExceptionUtils.findNestedThrowables(throwable).forEach(
+				t -> ExceptionUtils.pruneStackTrace(t, testClassNames));
 		}
 		super.executionFinished(testDescriptor, testExecutionResult);
 	}
 
-	private void pruneStackTrace(Throwable throwable) {
-		ExceptionUtils.pruneStackTrace(throwable, stackTraceElementFilter);
+	private static List<String> getTestClassNames(TestDescriptor testDescriptor) {
+		return Stream.of(testDescriptor.getSource(), testDescriptor.getParent().flatMap(TestDescriptor::getSource)) //
```
Comment (marcphilipp) [inline junit-platform-launcher/src/main/java/org/junit/platform/launcher/core/StackTracePruningEngineExecutionListener.java:51]: I think we should do this up to the engine descriptor. For example, to handle an exception thrown from a top-level `@BeforeEach` method with multiple levels of `@Nested` classes.

**Review by marcphilipp — CHANGES_REQUESTED** [review]

**Review by marcphilipp — APPROVED** [review]

**Review by sormuras — APPROVED** [review]
