### PR TITLE
Provide informative error message if parameterized test name pattern is invalid

### LINKED ISSUE #861: Create more informative exception for invalid parameterized test name
The name given to `@ParameterizedTest` is used by `MessageFormat` to create the final name. If the string contains an error, e.g. missing a closing bracket, the result is a not particularly informative exception:

```
java.lang.IllegalArgumentException: Unmatched braces in the pattern.

	at java.text.MessageFormat.applyPattern(MessageFormat.java:508)
	at java.text.MessageFormat.<init>(MessageFormat.java:362)
	at java.text.MessageFormat.format(MessageFormat.java:840)
	at org.junit.jupiter.params.ParameterizedTestNameFormatter.format(ParameterizedTestNameFormatter.java:39)
	at org.junit.jupiter.params.ParameterizedTestInvocationContext.getDisplayName(ParameterizedTestInvocationContext.java:35)
	at org.junit.jupiter.engine.descriptor.TestTemplateInvocationTestDescriptor.<init>(TestTemplateInvocationTestDescriptor.java:39)
	at org.junit.jupiter.engine.descriptor.TestTemplateTestDescriptor.createInvocationTestDescriptor(TestTemplateTestDescriptor.java:117)
	at org.junit.jupiter.engine.descriptor.TestTemplateTestDescriptor.lambda$execute$1(TestTemplateTestDescriptor.java:92)
```

It might be helpful to users to make it blatantly obvious where the problem comes from because I think the tendency is to look into the tests instead of at the setup.

### PR DESCRIPTION
**Pull request by nicolaiparlog**
Without this change an invalid test name pattern results in an error message that does not immediately point to the problem.

Before:

```
java.lang.IllegalArgumentException: Unmatched braces in the pattern.

	at java.text.MessageFormat.applyPattern(MessageFormat.java:508)
	at java.text.MessageFormat.<init>(MessageFormat.java:362)
	at java.text.MessageFormat.format(MessageFormat.java:840)
	at org.junit.jupiter.params.ParameterizedTestNameFormatter.format(ParameterizedTestNameFormatter.java:39)
	at org.junit.jupiter.params.ParameterizedTestInvocationContext.getDisplayName(ParameterizedTestInvocationContext.java:35)
	at org.junit.jupiter.engine.descriptor.TestTemplateInvocationTestDescriptor.<init>(TestTemplateInvocationTestDescriptor.java:39)
	at org.junit.jupiter.engine.descriptor.TestTemplateTestDescriptor.createInvocationTestDescriptor(TestTemplateTestDescriptor.java:117)
	at org.junit.jupiter.engine.descriptor.TestTemplateTestDescriptor.lambda$execute$1(TestTemplateTestDescriptor.java:92)
```

After:

```
org.junit.platform.commons.JUnitException: The naming pattern defined for the parameterized tests is invalid: Unmatched braces in the pattern.

	at org.junit.jupiter.params.ParameterizedTestNameFormatter.format(ParameterizedTestNameFormatter.java:54)
	at org.junit.jupiter.params.ParameterizedTestInvocationContext.getDisplayName(ParameterizedTestInvocationContext.java:35)
	at org.junit.jupiter.engine.descriptor.TestTemplateInvocationTestDescriptor.<init>(TestTemplateInvocationTestDescriptor.java:39)
	at org.junit.jupiter.engine.descriptor.TestTemplateTestDescriptor.createInvocationTestDescriptor(TestTemplateTestDescriptor.java:112)
	at org.junit.jupiter.engine.descriptor.TestTemplateTestDescriptor.lambda$execute$1(TestTemplateTestDescriptor.java:87)
	... more
Caused by: java.lang.IllegalArgumentException: Unmatched braces in the pattern.
	at java.text.MessageFormat.applyPattern(MessageFormat.java:508)
	at java.text.MessageFormat.<init>(MessageFormat.java:362)
	at java.text.MessageFormat.format(MessageFormat.java:840)
	at org.junit.jupiter.params.ParameterizedTestNameFormatter.format(ParameterizedTestNameFormatter.java:50)
	... 79 more
```

Closes #861.

---

I hereby agree to the terms of the JUnit Contributor License Agreement.

---

### Definition of Done

- [x] There are no TODOs left in the code
- [x] Method [preconditions](http://junit.org/junit5/docs/snapshot/api/org/junit/platform/commons/util/Preconditions.html) are checked and documented in the method's Javadoc
- [x] [Coding conventions](https://github.com/junit-team/junit5/blob/master/CONTRIBUTING.md#coding-conventions) (e.g. for logging) have been followed
- [x] Change is covered by [automated tests](https://github.com/junit-team/junit5/blob/master/CONTRIBUTING.md#tests)
- [x] Public API has [Javadoc](https://github.com/junit-team/junit5/blob/master/CONTRIBUTING.md#javadoc) and [`@API` annotations](http://junit.org/junit5/docs/snapshot/api/org/junit/platform/commons/meta/API.html)
- [x] Change is documented in the [User Guide](http://junit.org/junit5/docs/snapshot/user-guide/) and [Release Notes](http://junit.org/junit5/docs/snapshot/user-guide/#release-notes)
- [x] All [continuous integration builds](https://github.com/junit-team/junit5#continuous-integration-builds) pass

### CODE REVIEW

File: junit-jupiter-params/src/main/java/org/junit/jupiter/params/ParameterizedTestNameFormatter.java [hunk 1]
```diff
@@ -45,7 +46,13 @@ String format(int invocationIndex, Object... arguments) {
 			arguments[i] = StringUtils.nullSafeToString(arguments[i]);
 		}
 
-		return MessageFormat.format(result, arguments);
+		try {
+			return MessageFormat.format(result, arguments);
+		}
+		catch (IllegalArgumentException ex) {
+			String message = "The naming pattern defined for the parameterized tests is invalid: " + ex.getMessage();
```
Comment (marcphilipp) [inline junit-jupiter-params/src/main/java/org/junit/jupiter/params/ParameterizedTestNameFormatter.java]: Please don't append `ex.getMessage()` to the message.

Comment (nicolaiparlog) [inline junit-jupiter-params/src/main/java/org/junit/jupiter/params/ParameterizedTestNameFormatter.java]: I think there should be more information than "it didn't work". What about "Check the nested exception fore details."?

Comment (marcphilipp) [inline junit-jupiter-params/src/main/java/org/junit/jupiter/params/ParameterizedTestNameFormatter.java]: Don't you think Java developers should be trained to do so anyway? Nevertheless, I would be ok with adding that sentence.

Comment (nicolaiparlog) [inline junit-jupiter-params/src/main/java/org/junit/jupiter/params/ParameterizedTestNameFormatter.java]: They definitely should but you know how it is. Maybe somebody's new or tired or under a lot of pressure - this make it a little clearer.
